'use client';

import React from 'react';
import { ShieldCheck, ShieldAlert, RotateCw, Hash } from 'lucide-react';
import type { ChainVerificationResult, AuditLogEntry } from '@/lib/audit/logger';

interface CryptographicIntegritySectionProps {
  tenantId: string;
  verificationResult: ChainVerificationResult | null;
  isVerifying: boolean;
  onVerifyChain: () => void;
  logs: AuditLogEntry[];
}

/**
 * Displays only cryptographic evidence that is actually persisted on audit records.
 * It does not synthesize historical checks, success rates, block counts, or compliance claims.
 */
export default function CryptographicIntegritySection({
  tenantId,
  verificationResult,
  isVerifying,
  onVerifyChain,
  logs,
}: CryptographicIntegritySectionProps) {
  const storedDigestCount = logs.filter((log) => Boolean(log.hash && log.previousHash)).length;
  const unverifiedCount = Math.max(0, logs.length - storedDigestCount);
  const hasDigestEvidence = storedDigestCount > 0;
  const hasMismatch =
    Boolean(verificationResult) &&
    !verificationResult?.isValid &&
    verificationResult?.brokenAtIndex !== null;

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
      <div
        className={
          hasMismatch
            ? 'p-5 bg-rose-50 border-b border-rose-200'
            : 'p-5 bg-slate-50 border-b border-slate-200'
        }
      >
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div
              className={
                hasMismatch
                  ? 'w-10 h-10 rounded-xl bg-rose-600 text-white flex items-center justify-center'
                  : 'w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center'
              }
            >
              {hasMismatch ? <ShieldAlert className="w-5 h-5" /> : <ShieldCheck className="w-5 h-5" />}
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">
                {hasMismatch
                  ? 'Stored Audit Digest Mismatch Detected'
                  : hasDigestEvidence && verificationResult?.isValid
                  ? 'Stored Audit Digests Validated'
                  : 'Audit Integrity Evidence'}
              </h2>
              <p className="text-xs text-slate-600 mt-1">
                Tenant <code className="font-mono font-semibold">{tenantId}</code>. Only hashes already
                stored by an authoritative service are validated; missing digests are reported as
                unverified rather than generated by the browser.
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onVerifyChain}
            disabled={isVerifying}
            className="px-3.5 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 disabled:opacity-60 text-white text-xs font-bold flex items-center gap-1.5"
          >
            <RotateCw className={isVerifying ? 'w-3.5 h-3.5 animate-spin' : 'w-3.5 h-3.5'} />
            {isVerifying ? 'Validating…' : 'Validate Stored Digests'}
          </button>
        </div>
      </div>

      <div className="p-5 grid grid-cols-1 sm:grid-cols-3 gap-3">
        <div className="rounded-xl border border-slate-200 p-4">
          <div className="text-[10px] uppercase tracking-wide text-slate-500 font-bold">Audit records loaded</div>
          <div className="text-2xl font-black text-slate-900 mt-1">{logs.length}</div>
        </div>

        <div className="rounded-xl border border-slate-200 p-4">
          <div className="text-[10px] uppercase tracking-wide text-slate-500 font-bold flex items-center gap-1">
            <Hash className="w-3 h-3" /> Stored digest records
          </div>
          <div className="text-2xl font-black text-slate-900 mt-1">{storedDigestCount}</div>
          <div className="text-[10px] text-slate-500 mt-1">
            {verificationResult?.totalLogsChecked || 0} checked in the latest validation
          </div>
        </div>

        <div className="rounded-xl border border-slate-200 p-4">
          <div className="text-[10px] uppercase tracking-wide text-slate-500 font-bold">Unverified records</div>
          <div className="text-2xl font-black text-slate-900 mt-1">{unverifiedCount}</div>
          <div className="text-[10px] text-slate-500 mt-1">
            No client-generated digest is substituted for missing evidence.
          </div>
        </div>
      </div>

      <div className="px-5 pb-5 text-[11px] text-slate-500">
        This panel is engineering evidence only. It does not establish regulatory compliance,
        certification, or a globally chained ledger unless authoritative stored hashes exist for
        the records being evaluated.
      </div>
    </div>
  );
}
