/**
 * G-HIMS Specialty-Aware Clinical Workflow Engine
 * Orchestrating the 4-Stage Clinical Enrichment Pipeline:
 * 1. Nursing Care / Triage
 * 2. General Assessment (MO Intake)
 * 3. Disease-Centric Structured Intake (Cardiology & Specialties)
 * 4. Consultant Specialist (Investigations, SOAP, Lifestyle, Med Reconciliation, Route)
 */

import {
  ClinicalSpecialty,
  NursingTriageIntake,
  GeneralAssessmentMoIntake,
  CardiologyStructuredIntake,
  PulmonologyStructuredIntake,
  NeurologyStructuredIntake,
  StructuredSpecialtyIntakeData,
  SpecialInvestigationItem,
  StructuredSoapDocumentation,
  LifestyleModificationPrescription,
  ReconciledMedicationItem,
  ClinicalRoutingDecision,
  LongitudinalEncounterRecord,
} from '@/types/specialty-clinical-workflow';

export class SpecialtyWorkflowEngine {
  /**
   * Generates a sample pre-loaded longitudinal cardiology encounter
   */
  public static createInitialDemoEncounter(): LongitudinalEncounterRecord {
    const now = Date.now();
    return {
      encounterId: 'enc-cardio-2026-8801',
      tenantId: 'central-metro-hospital',
      patientId: 'pat-102',
      mrn: 'MRN-20260820-9124',
      patientName: 'Tariq Mehmood',
      gender: 'Male',
      age: 58,
      encounterDate: now - 3600000 * 2,
      specialty: 'CARDIOLOGY',
      currentWorkflowStage: 'CONSULTANT_EVALUATION',

      // Stage 1: Nursing Care / Triage
      nursingTriage: {
        assessedAt: now - 3600000 * 2,
        nurseId: 'nrs-104',
        nurseName: 'Staff Nurse R. Chen (RN)',
        chiefComplaint: 'Post-PCI retrosternal chest pressure and dyspnea on walking 50 meters',
        symptomDuration: '3 days, worsening since morning',
        painScale: 6,
        fallRiskScore: 2,
        consciousnessAvpu: 'ALERT',
        glasgowComaScale: 15,
        vitals: {
          heartRate: 94,
          systolicBp: 146,
          diastolicBp: 92,
          respiratoryRate: 20,
          temperatureCelsius: 36.8,
          spo2Percent: 95,
          onSupplementalOxygen: false,
          news2Score: 3,
          clinicalRisk: 'LOW',
          triageCategory: 'YELLOW_URGENT',
        },
        knownAllergies: [
          { allergen: 'Penicillin', reaction: 'Urticaria & Bronchospasm', severity: 'SEVERE_ANAPHYLAXIS' },
          { allergen: 'Sulfa Drugs', reaction: 'Skin Rash', severity: 'MILD' },
        ],
        redFlagAlerts: ['Cardiac Troponin testing required STAT', 'Ischemic symptoms in post-PCI patient'],
        intakeNotes: 'Patient arrived with family. Reports tightening retrosternal pain radiating to left jaw.',
      },

      // Stage 2: General Assessment / MO Intake
      generalAssessment: {
        assessedAt: now - 3600000 * 1.5,
        moId: 'mo-201',
        moName: 'Dr. Ali Raza (Medical Officer)',
        historyOfPresentIllness:
          '58yo male with known CAD s/p PCI to LAD (6 months ago), presents with recurrent episodes of substernal tightness occurring after walking up stairs or carrying groceries. Relieved within 5 minutes of rest. No syncope.',
        pastMedicalHistory: [
          'Coronary Artery Disease (CAD) - Stent placed Oct 2025',
          'Primary Hypertension (12 years)',
          'Type 2 Diabetes Mellitus (8 years)',
          'Mixed Dyslipidemia',
        ],
        pastSurgicalHistory: ['Percutaneous Coronary Intervention (PCI to LAD) - Oct 2025', 'Appendectomy - 2012'],
        socialHistory: {
          smokingStatus: 'FORMER',
          packYears: 20,
          alcoholUse: 'NONE',
          occupation: 'Civil Engineer (Retired)',
          exerciseLevel: 'SEDENTARY',
        },
        reviewOfSystems: {
          constitutional: 'No fever, chills, or unexplained weight loss.',
          cardiovascular: 'Positive for chest pressure on exertion, occasional palpitations. Denies orthopnea.',
          respiratory: 'Shortness of breath on moderate exertion. No chronic cough or wheezing.',
          gastrointestinal: 'No abdominal pain, melena, or hematochezia.',
          neurological: 'Denies dizziness, syncope, numbness, or motor weakness.',
          musculoskeletal: 'No joint swelling or calf tenderness.',
          genitourinary: 'No dysuria or hematuria.',
        },
        baselineInvestigations: [
          { testName: 'Complete Blood Count (CBC)', status: 'RESULTED', value: 'Hb 13.8 g/dL, WBC 7.2 k/uL', isAbnormal: false },
          { testName: 'Basic Metabolic Panel (BMP)', status: 'RESULTED', value: 'Creatinine 1.1 mg/dL, K+ 4.4 mEq/L', isAbnormal: false },
          { testName: 'Random Blood Glucose', status: 'RESULTED', value: '158 mg/dL', isAbnormal: true },
          { testName: 'Point-of-Care 12-Lead ECG', status: 'RESULTED', value: 'Sinus rhythm @ 94bpm, T-wave flattening in V4-V6', isAbnormal: true },
        ],
        provisionalDiagnoses: [
          { code: 'I20.9', description: 'Angina pectoris, unspecified (Post-PCI)' },
          { code: 'I10', description: 'Essential (primary) hypertension' },
          { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications' },
        ],
        recommendedSpecialty: 'CARDIOLOGY',
        urgencyLevel: 'PRIORITY',
        preliminaryTriageNotes: 'Stable vitals, but concerning for in-stent restenosis or progressive CAD. Routed to Cardiology Consultant Desk.',
      },

      // Stage 3: Disease-Centric Structured Intake (Cardiology)
      specialtyIntake: {
        specialty: 'CARDIOLOGY',
        recordedAt: now - 3600000 * 1,
        recordedBy: 'Dr. Sarah Jenkins, MD & Cardiac Fellow',
        cardiacHistory: {
          priorMyocardialInfarction: true,
          priorMiYear: 2025,
          knownCoronaryArteryDisease: true,
          heartFailureHistory: false,
          nyhaBaselineClass: 'II',
          arrhythmiaHistory: false,
          valvularHeartDisease: false,
          hypertensionYears: 12,
          dyslipidemiaYears: 10,
          diabetesMellitusYears: 8,
        },
        symptoms: {
          chestPain: {
            hasChestPain: true,
            provocation: 'Physical exertion (walking >50m, climbing 1 flight of stairs), cold air exposure',
            palliation: 'Rest (resolves in 3-5 minutes), Sublingual Nitroglycerin spray',
            quality: 'CRUSHING_PRESSURE',
            regionAndRadiation: ['Retrosternal / Mid-chest', 'Radiation to Left Inner Arm', 'Mild Left Mandibular Radiation'],
            severityScale: 6,
            temporalPattern: 'Episodic, lasting 3-8 minutes per episode, 2-3 episodes per day',
            associatedDiaphoresis: true,
            associatedNausea: false,
          },
          dyspneaNyhaClass: 'CLASS_II_SLIGHT_LIMITATION',
          palpitations: {
            present: true,
            pattern: 'RAPID_REGULAR',
            frequency: 'Brief runs during exertion',
          },
          syncopeOrPresyncope: {
            hasSyncope: false,
            episodesCountLast6Months: 0,
            exertionalTrigger: false,
          },
          intermittentClaudication: {
            present: false,
          },
        },
        cardiacQuestions: {
          orthopneaPillowsCount: 1,
          paroxysmalNocturnalDyspnea: false,
          bilateralPedalEdema: 'GRADE_1_MILD',
          recentWeightGainLastWeekKg: 0.5,
          exerciseToleranceEquivalentMets: 3.5, // Can walk on level ground at 3 mph
        },
        surgicalHistory: {
          priorPciWithStents: true,
          pciVessels: ['LAD (Mid-Left Anterior Descending) with 3.0x24mm DES'],
          pciYear: 2025,
          stentTypes: 'DRUG_ELUTING',
          priorCabg: false,
          cardiacDeviceImplants: 'NONE',
        },
        medicationHistory: {
          onAntiplatelets: true,
          antiplateletDrugs: ['Aspirin 81mg Daily', 'Clopidogrel 75mg Daily (Dual Antiplatelet Therapy - DAPT)'],
          onBetaBlockers: true,
          betaBlockerDrug: 'Metoprolol Succinate 25mg Daily',
          onAceiArbArni: true,
          aceiDrug: 'Ramipril 5mg Daily',
          onStatins: true,
          statinDrug: 'Atorvastatin 40mg Daily',
          onAnticoagulants: false,
          onDiuretics: false,
          selfReportedAdherencePercent: 90,
        },
        familyCardiacHistory: {
          prematureCadFirstDegreeRelative: true,
          suddenCardiacDeathHistory: false,
          familialHypercholesterolemia: false,
          cardiomyopathyFamilyHistory: false,
          affectedRelativesDetails: 'Father had fatal MI at age 52; elder brother underwent CABG at age 54.',
        },
      },

      // Stage 4: Consultant Specialist (Cardiologist)
      consultantDocumentation: {
        specialInvestigations: [
          {
            id: 'inv-card-01',
            code: 'LAB-TROP-HS',
            name: 'High-Sensitivity Cardiac Troponin I (hs-cTnI)',
            modality: 'LAB_CARDIAC',
            indication: 'Rule out Acute Coronary Syndrome / Non-STEMI',
            urgency: 'STAT',
            status: 'FINALIZED',
            orderedAt: now - 3600000,
            resultSummary: '0.042 ng/mL (Mildly Elevated >0.034 upper ref limit)',
            keyFindings: { troponinValue: '0.042 ng/mL (Elevated)' },
            criticalAlert: true,
          },
          {
            id: 'inv-card-02',
            code: 'CARD-ECG-12',
            name: '12-Lead Electrocardiogram with Vector Analysis',
            modality: 'ECG',
            indication: 'Assess ST-T dynamic changes',
            urgency: 'STAT',
            status: 'FINALIZED',
            orderedAt: now - 3600000,
            resultSummary: 'Sinus Rhythm at 92 bpm, 1mm ST depression in V4-V6 during discomfort',
            keyFindings: { ecgRhythm: 'Sinus rhythm with dynamic lateral ST depressions' },
          },
          {
            id: 'inv-card-03',
            code: 'CARD-ECHO-TTE',
            name: 'Transthoracic Echocardiogram (2D + Doppler + Strain)',
            modality: 'ECHO',
            indication: 'Assess left ventricular systolic function and regional wall motion',
            urgency: 'URGENT',
            status: 'FINALIZED',
            orderedAt: now - 3600000 * 0.8,
            resultSummary: 'LVEF 50%. Hypokinesia of mid-anterior septum. No significant valvular regurgitation.',
            keyFindings: { echoLvefPercent: 50 },
          },
          {
            id: 'inv-card-04',
            code: 'LAB-NT-PROBNP',
            name: 'N-Terminal pro-B-type Natriuretic Peptide (NT-proBNP)',
            modality: 'LAB_CARDIAC',
            indication: 'Evaluate neurohormonal ventricular stretch',
            urgency: 'ROUTINE',
            status: 'FINALIZED',
            orderedAt: now - 3600000 * 0.8,
            resultSummary: '420 pg/mL (Normal <450 in non-acute setting)',
            keyFindings: { ntProBnpValue: '420 pg/mL' },
          },
        ],
        soap: {
          subjective:
            '58-year-old male s/p PCI to LAD in 10/2025 presents with 3-day history of crescendo exertional chest pressure (6/10) radiating to left arm, occurring at lower workloads than baseline. Sublingual nitroglycerin provides prompt relief in 3 mins. DAPT adherence is good.',
          objective:
            'BP: 146/92 mmHg, HR: 94 bpm regular, SpO2: 95% on room air. JVP normal at 3cm above sternal angle. Heart: Regular rate and rhythm, S1/S2 normal, S4 gallop heard at apex, no murmurs. Lungs: Clear bilaterally, no crackles. Extremities: Trace bilateral pedal edema (1+). hs-cTnI: 0.042 ng/mL (elevated). ECG: Lateral ST depressions.',
          assessment:
            '1. Unstable Angina / Non-ST-Elevation Acute Coronary Syndrome (NSTE-ACS) - Intermediate to High Risk, likely LAD in-stent restenosis or new lesion.\n2. Essential Hypertension, suboptimally controlled.\n3. Type 2 Diabetes Mellitus.\n4. Hyperlipidemia, on moderate statin.',
          plan:
            '1. Urgent Coronary Angiography (scheduled for next available cath lab slot today).\n2. Optimize Anti-ischemic & Medical Therapy:\n   - Up-titrate Metoprolol Succinate from 25mg to 50mg PO Daily.\n   - Switch Clopidogrel to Ticagrelor 90mg PO BID (Loading 180mg).\n   - Up-titrate Atorvastatin to High-Intensity 80mg PO QHS.\n   - Start Isosorbide Mononitrate ER 30mg PO Daily.\n3. Continuous telemetry monitoring in CCU/Stepdown bed.\n4. Strict low-sodium, cardiac rehabilitation referral post-intervention.',
          primaryDiagnosis: {
            icd10Code: 'I20.0',
            title: 'Unstable angina (Intermediate/High-Risk NSTE-ACS)',
            isChronic: false,
          },
          secondaryDiagnoses: [
            { icd10Code: 'I25.10', title: 'Atherosclerotic heart disease of native coronary artery' },
            { icd10Code: 'Z95.5', title: 'Presence of coronary angioplasty implant and stent' },
            { icd10Code: 'I10', title: 'Essential (primary) hypertension' },
          ],
          clinicalRiskScores: {
            ascvd10YearRiskPercent: 28.4,
            nyhaFunctionalClass: 'CLASS_II',
            cha2ds2VascScore: 3,
            framinghamScore: 24,
          },
          cptBillingProcedures: [
            { code: '99215', description: 'Comprehensive Outpatient Consultation (High Medical Complexity)', fee: 240.0 },
            { code: '93000', description: '12-Lead Electrocardiogram Interpretation and Report', fee: 55.0 },
            { code: '93306', description: 'Transthoracic Echocardiography with Spectral & Color Doppler', fee: 420.0 },
          ],
          consultantId: 'doc-sarah-jenkins',
          consultantName: 'Dr. Sarah Jenkins, MD, FACC',
          consultantSpecialty: 'Cardiovascular Medicine & Interventional Cardiology',
          signedAt: now - 3600000 * 0.3,
          isSigned: true,
        },
        lifestyleModification: {
          dietaryPlan: {
            sodiumRestrictionGramsPerDay: 2.0,
            fluidRestrictionLitersPerDay: 2.0,
            mediterraneanDietAdvised: true,
            diabeticCarbRestriction: true,
          },
          exerciseAndRehab: {
            cardiacRehabEnrolled: true,
            exerciseFrequencyDaysPerWeek: 5,
            targetMinutesPerSession: 30,
            prescribedIntensity: 'SUPERVISED_CARDIAC_REHAB',
            contraindicationsWarning: 'Avoid unmonitored strenuous isometric exertion pending cath lab revascularization.',
          },
          smokingCessationPlan: {
            activeIntervention: true,
            nicotineReplacementTherapy: false,
            counselingReferral: true,
          },
          weightManagementGoalKg: 78,
          prescribedAt: now - 3600000 * 0.3,
        },
        medications: [
          {
            id: 'med-rec-01',
            drugName: 'Aspirin (Enteric Coated)',
            dosage: '81 mg',
            route: 'ORAL',
            frequency: 'Once Daily (with morning meal)',
            indication: 'Secondary CAD Prevention & Antiplatelet',
            reconciliationAction: 'CONTINUED_UNCHANGED',
            durationDays: 365,
            dispensedStatus: 'VERIFIED',
          },
          {
            id: 'med-rec-02',
            drugName: 'Ticagrelor (Brilinta)',
            dosage: '90 mg (Loaded 180mg STAT)',
            route: 'ORAL',
            frequency: 'Twice Daily (BID)',
            indication: 'Potent P2Y12 Antiplatelet for NSTE-ACS',
            reconciliationAction: 'NEWLY_PRESCRIBED',
            potentialInteractionsAlert: 'Replaced Clopidogrel 75mg. Advise regarding mild dyspnea risk.',
            durationDays: 365,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-rec-03',
            drugName: 'Metoprolol Succinate ER',
            dosage: '50 mg',
            route: 'ORAL',
            frequency: 'Once Daily (increased from 25mg)',
            indication: 'Anti-ischemic, Rate Control & Cardioprotection',
            reconciliationAction: 'MODIFIED_DOSE',
            durationDays: 90,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-rec-04',
            drugName: 'Atorvastatin Calcium (Lipitor)',
            dosage: '80 mg',
            route: 'ORAL',
            frequency: 'Once Daily at Bedtime (QHS)',
            indication: 'High-Intensity Statin Plaque Stabilization',
            reconciliationAction: 'MODIFIED_DOSE',
            durationDays: 90,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-rec-05',
            drugName: 'Isosorbide Mononitrate ER',
            dosage: '30 mg',
            route: 'ORAL',
            frequency: 'Once Daily in the Morning',
            indication: 'Long-Acting Anti-Anginal Vasodilator',
            reconciliationAction: 'NEWLY_PRESCRIBED',
            durationDays: 30,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-rec-06',
            drugName: 'Clopidogrel (Plavix) 75mg',
            dosage: '75 mg',
            route: 'ORAL',
            frequency: 'Once Daily',
            indication: 'Previous Antiplatelet',
            reconciliationAction: 'DISCONTINUED_HOLD',
            discontinuationReason: 'Escalated to Ticagrelor 90mg BID for acute ischemic symptoms.',
            durationDays: 0,
            dispensedStatus: 'DISPENSED',
          },
        ],
        routing: {
          destinationType: 'CATH_LAB_ADMISSION',
          targetDepartment: 'Interventional Cardiology & Cardiac Catheterization Lab',
          targetSpecialistId: 'doc-sarah-jenkins',
          targetSpecialistName: 'Dr. Sarah Jenkins, MD, FACC',
          revisitIntervalDays: 0,
          scheduledRevisitDate: 'Immediate Same-Day Procedure',
          routingPriority: 'STAT_EMERGENCY',
          clinicalHandoffSummary:
            'Patient accepted for urgent diagnostic coronary angiography +/- PCI for Intermediate/High-Risk NSTE-ACS. Bed reserved in CCU-Room 304. Pre-procedure labs and consent completed.',
          routedAt: now - 3600000 * 0.2,
          routedBy: 'Dr. Sarah Jenkins, MD',
        },
      },

      lifecycleEvents: [
        {
          eventId: 'evt-01',
          eventType: 'clinical.patient.admitted_triage',
          stageName: 'Nursing Care / Triage',
          timestamp: now - 3600000 * 2,
          actor: 'Staff Nurse R. Chen (RN)',
          summary: 'Patient checked in. NEWS2 Score calculated as 3 (Low risk). Yellow Triage assigned.',
        },
        {
          eventId: 'evt-02',
          eventType: 'clinical.mo_assessment.completed',
          stageName: 'General Assessment (MO Intake)',
          timestamp: now - 3600000 * 1.5,
          actor: 'Dr. Ali Raza (Medical Officer)',
          summary: 'Complete HPI and baseline investigations reviewed. Provisional diagnosis of unstable angina recorded.',
        },
        {
          eventId: 'evt-03',
          eventType: 'clinical.cardiology_intake.structured',
          stageName: 'Disease-Centric Structured Intake',
          timestamp: now - 3600000 * 1,
          actor: 'Dr. Sarah Jenkins, MD',
          summary: 'Cardiac PQRST pain profile, prior LAD stent history, and family CAD history captured into structured MPI.',
        },
        {
          eventId: 'evt-04',
          eventType: 'clinical.consultant_soap.signed',
          stageName: 'Consultant Specialist (Cardiologist)',
          timestamp: now - 3600000 * 0.3,
          actor: 'Dr. Sarah Jenkins, MD, FACC',
          summary: 'Consultant SOAP note cryptographically signed with ICD-10 I20.0 and CPT 99215.',
        },
        {
          eventId: 'evt-05',
          eventType: 'clinical.medication_reconciliation.completed',
          stageName: 'Medication Reconciliation',
          timestamp: now - 3600000 * 0.25,
          actor: 'Dr. Sarah Jenkins, MD & Clinical Pharmacist',
          summary: '6 medications reconciled. Clopidogrel replaced with Ticagrelor 90mg BID. High-dose Statin initiated.',
        },
        {
          eventId: 'evt-06',
          eventType: 'clinical.patient_routed.cath_lab',
          stageName: 'Clinical Routing',
          timestamp: now - 3600000 * 0.2,
          actor: 'Dr. Sarah Jenkins, MD',
          summary: 'Patient routed STAT to Cardiac Catheterization Lab for urgent coronary angiography.',
        },
      ],
    };
  }

  /**
   * Pulmonology Default Schema Builder
   */
  public static createPulmonologyDemoEncounter(): LongitudinalEncounterRecord {
    const now = Date.now();
    return {
      encounterId: 'enc-pulm-2026-9042',
      tenantId: 'central-metro-hospital',
      patientId: 'pat-105',
      mrn: 'MRN-20260820-3391',
      patientName: 'Khadija Bibi',
      gender: 'Female',
      age: 64,
      encounterDate: now - 3600000 * 3,
      specialty: 'PULMONOLOGY',
      currentWorkflowStage: 'CONSULTANT_EVALUATION',
      nursingTriage: {
        assessedAt: now - 3600000 * 3,
        nurseId: 'nrs-106',
        nurseName: 'Nurse Amina Tariq (RN)',
        chiefComplaint: 'Progressive exertional breathlessness and productive cough with purulent sputum for 2 weeks',
        symptomDuration: '14 days',
        painScale: 2,
        fallRiskScore: 1,
        consciousnessAvpu: 'ALERT',
        glasgowComaScale: 15,
        vitals: {
          heartRate: 102,
          systolicBp: 132,
          diastolicBp: 84,
          respiratoryRate: 24,
          temperatureCelsius: 37.8,
          spo2Percent: 91,
          onSupplementalOxygen: true,
          oxygenFlowRateLpm: 2,
          news2Score: 6,
          clinicalRisk: 'MEDIUM',
          triageCategory: 'ORANGE_VERY_URGENT',
        },
        knownAllergies: [{ allergen: 'Aspirin / NSAIDs', reaction: 'Bronchospasm', severity: 'MODERATE' }],
        redFlagAlerts: ['SpO2 91% on room air (responsive to 2L O2)', 'Tachypneic RR 24'],
        intakeNotes: 'Wheezing audible on expiration. Sputum is thick yellowish-green.',
      },
      generalAssessment: {
        assessedAt: now - 3600000 * 2.2,
        moId: 'mo-202',
        moName: 'Dr. Zainab Bilal (Medical Officer)',
        historyOfPresentIllness: '64yo female with known Severe COPD (GOLD Grade 3) presenting with acute infective exacerbation.',
        pastMedicalHistory: ['Chronic Obstructive Pulmonary Disease (COPD) - 9 yrs', 'Osteoporosis'],
        pastSurgicalHistory: ['Total Knee Arthroplasty (2018)'],
        socialHistory: {
          smokingStatus: 'FORMER',
          packYears: 35,
          alcoholUse: 'NONE',
          occupation: 'Homemaker',
          exerciseLevel: 'SEDENTARY',
        },
        reviewOfSystems: {
          constitutional: 'Low-grade fever, malaise.',
          cardiovascular: 'No chest pain or orthopnea.',
          respiratory: 'Marked wheezing, purulent sputum, mMRC grade 3.',
          gastrointestinal: 'Normal appetite, no nausea.',
          neurological: 'Alert and oriented.',
          musculoskeletal: 'Mild knee stiffness.',
          genitourinary: 'Unremarkable.',
        },
        baselineInvestigations: [
          { testName: 'Chest X-Ray (PA View)', status: 'RESULTED', value: 'Hyperinflated lungs with flattened diaphragms; right base opacity', isAbnormal: true },
          { testName: 'Arterial Blood Gas (ABG)', status: 'RESULTED', value: 'pH 7.36, PaCO2 48 mmHg, PaO2 68 mmHg, HCO3 28 mEq/L', isAbnormal: true },
          { testName: 'Complete Blood Count (CBC)', status: 'RESULTED', value: 'WBC 13.4 k/uL (Neutrophil predominance 82%)', isAbnormal: true },
        ],
        provisionalDiagnoses: [
          { code: 'J44.1', description: 'Chronic obstructive pulmonary disease with acute exacerbation' },
          { code: 'J18.9', description: 'Community-acquired pneumonia, unspecified organism' },
        ],
        recommendedSpecialty: 'PULMONOLOGY',
        urgencyLevel: 'PRIORITY',
        preliminaryTriageNotes: 'Acute COPD Exacerbation with secondary bacterial bronchitis/pneumonia. Fast-tracked to Pulmonology Consultant.',
      },
      specialtyIntake: {
        specialty: 'PULMONOLOGY',
        recordedAt: now - 3600000 * 1.5,
        recordedBy: 'Dr. Farhan Qureshi (Pulmonologist)',
        dyspneaMmrcScale: 'GRADE_3',
        coughCharacteristics: {
          hasCough: true,
          durationWeeks: 2,
          sputumType: 'PURULENT_YELLOW_GREEN',
          nocturnalWorsening: true,
        },
        wheezingAndTriggers: {
          present: true,
          triggers: ['Viral upper respiratory tract infection', 'Cold winter morning air', 'Dust'],
        },
        priorAsthmaOrCopdDiagnosis: true,
        historyOfPneumothoraxOrTb: false,
        inhalerTechniqueAndAdherence: 'Uses Formoterol/Budesonide DPI, but forgets morning dose 30% of the time. Poor inspiratory effort noted.',
      },
      consultantDocumentation: {
        specialInvestigations: [
          {
            id: 'inv-pulm-01',
            code: 'PULM-SPO2-MONITOR',
            name: 'Continuous Pulse Oximetry & SpO2 Titration Target 88-92%',
            modality: 'IMAGING',
            indication: 'Maintain target SpO2 in chronic hypercapnic COPD',
            urgency: 'STAT',
            status: 'FINALIZED',
            orderedAt: now - 3600000 * 1.2,
            resultSummary: 'Target SpO2 maintained at 90-92% on 2 L/min nasal cannula.',
          },
          {
            id: 'inv-pulm-02',
            code: 'LAB-SPUTUM-CS',
            name: 'Sputum Gram Stain, Culture and Antimicrobial Sensitivity',
            modality: 'LAB_CARDIAC',
            indication: 'Identify bacterial pathogen in purulent exacerbation',
            urgency: 'URGENT',
            status: 'IN_PROCESSING',
            orderedAt: now - 3600000 * 1.2,
            resultSummary: 'Gram negative coccobacilli observed (presumptive Haemophilus influenzae). Culture pending.',
          },
        ],
        soap: {
          subjective: '64yo female with severe COPD presents with 2-week history of worsening breathlessness (mMRC Grade 3) and purulent sputum production.',
          objective: 'Vitals: BP 132/84, HR 102, RR 24, Temp 37.8°C, SpO2 91% room air -> 92% on 2L O2. Diffuse expiratory wheeze with right basal coarse crackles.',
          assessment: '1. Acute Exacerbation of Chronic Obstructive Pulmonary Disease (AECOPD) - Infective etiology.\n2. Chronic respiratory failure Type 2 (compensated).',
          plan: '1. Nebulized Salbutamol 2.5mg + Ipratropium 0.5mg Q6H.\n2. Oral Prednisolone 40mg daily for 5 days.\n3. Amoxicillin/Clavulanate 1g PO BID for 7 days.\n4. Oxygen titrated to maintain SpO2 88-92%.\n5. Pulmonary Rehabilitation referral once stabilized.',
          primaryDiagnosis: {
            icd10Code: 'J44.1',
            title: 'Chronic obstructive pulmonary disease with acute exacerbation',
            isChronic: true,
          },
          secondaryDiagnoses: [{ icd10Code: 'J96.02', title: 'Acute respiratory failure with hypercapnia' }],
          clinicalRiskScores: {
            nyhaFunctionalClass: 'CLASS_III',
          },
          cptBillingProcedures: [
            { code: '99214', description: 'Office Consultation (Detailed Complexity)', fee: 180.0 },
            { code: '94640', description: 'Non-pressurized Inhalation Treatment for Acute Airway Obstruction', fee: 45.0 },
          ],
          consultantId: 'doc-farhan-qureshi',
          consultantName: 'Dr. Farhan Qureshi, MD, FCCP',
          consultantSpecialty: 'Pulmonology & Critical Care Medicine',
          signedAt: now - 3600000 * 0.5,
          isSigned: true,
        },
        lifestyleModification: {
          dietaryPlan: {
            sodiumRestrictionGramsPerDay: 2.5,
            mediterraneanDietAdvised: true,
            diabeticCarbRestriction: false,
          },
          exerciseAndRehab: {
            cardiacRehabEnrolled: false,
            exerciseFrequencyDaysPerWeek: 3,
            targetMinutesPerSession: 20,
            prescribedIntensity: 'LIGHT_WALKING',
            contraindicationsWarning: 'Stop if SpO2 drops below 88% or severe breathlessness occurs.',
          },
          smokingCessationPlan: {
            activeIntervention: false,
            nicotineReplacementTherapy: false,
            counselingReferral: false,
          },
          prescribedAt: now - 3600000 * 0.5,
        },
        medications: [
          {
            id: 'med-pulm-01',
            drugName: 'Nebulized Ipratropium / Salbutamol (Combivent)',
            dosage: '0.5mg / 2.5mg in 3mL',
            route: 'INHALATION',
            frequency: 'Every 6 hours STAT',
            indication: 'Acute Bronchodilation',
            reconciliationAction: 'NEWLY_PRESCRIBED',
            durationDays: 5,
            dispensedStatus: 'VERIFIED',
          },
          {
            id: 'med-pulm-02',
            drugName: 'Prednisolone Tablets',
            dosage: '40 mg',
            route: 'ORAL',
            frequency: 'Once Daily with morning breakfast',
            indication: 'Airway anti-inflammatory for AECOPD',
            reconciliationAction: 'NEWLY_PRESCRIBED',
            durationDays: 5,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-pulm-03',
            drugName: 'Amoxicillin / Clavulanate (Augmentin)',
            dosage: '1 g (875/125mg)',
            route: 'ORAL',
            frequency: 'Twice Daily (every 12 hours)',
            indication: 'Targeting Haemophilus and Streptococcus in purulent AECOPD',
            reconciliationAction: 'NEWLY_PRESCRIBED',
            durationDays: 7,
            dispensedStatus: 'PENDING_PHARMACY',
          },
          {
            id: 'med-pulm-04',
            drugName: 'Budesonide / Formoterol (Symbicort Turbuhaler)',
            dosage: '160/4.5 mcg',
            route: 'INHALATION',
            frequency: '2 puffs Twice Daily',
            indication: 'Maintenance ICS/LABA',
            reconciliationAction: 'CONTINUED_UNCHANGED',
            durationDays: 30,
            dispensedStatus: 'VERIFIED',
          },
        ],
        routing: {
          destinationType: 'INPATIENT_WARD',
          targetDepartment: 'Respiratory High Dependency Unit (HDU)',
          targetSpecialistId: 'doc-farhan-qureshi',
          targetSpecialistName: 'Dr. Farhan Qureshi, MD',
          routingPriority: 'PRIORITY',
          clinicalHandoffSummary: 'Admit to Respiratory HDU for close SpO2 monitoring, nebulization protocol, and IV steroid review if oral tolerance diminishes.',
          routedAt: now - 3600000 * 0.4,
          routedBy: 'Dr. Farhan Qureshi, MD',
        },
      },
      lifecycleEvents: [
        {
          eventId: 'evt-pulm-01',
          eventType: 'clinical.patient.admitted_triage',
          stageName: 'Nursing Care / Triage',
          timestamp: now - 3600000 * 3,
          actor: 'Nurse Amina Tariq (RN)',
          summary: 'Orange triage assigned due to SpO2 91% and tachypnea. Supplemental O2 started.',
        },
        {
          eventId: 'evt-pulm-02',
          eventType: 'clinical.mo_assessment.completed',
          stageName: 'General Assessment (MO Intake)',
          timestamp: now - 3600000 * 2.2,
          actor: 'Dr. Zainab Bilal (MO)',
          summary: 'CXR and ABG evaluated. Routed to Pulmonology.',
        },
        {
          eventId: 'evt-pulm-03',
          eventType: 'clinical.pulmonology_intake.structured',
          stageName: 'Disease-Centric Structured Intake',
          timestamp: now - 3600000 * 1.5,
          actor: 'Dr. Farhan Qureshi, MD',
          summary: 'mMRC Grade 3 dyspnea and purulent sputum characteristics recorded.',
        },
        {
          eventId: 'evt-pulm-04',
          eventType: 'clinical.consultant_soap.signed',
          stageName: 'Consultant Specialist (Pulmonologist)',
          timestamp: now - 3600000 * 0.5,
          actor: 'Dr. Farhan Qureshi, MD, FCCP',
          summary: 'AECOPD management plan formalized and signed with ICD-10 J44.1.',
        },
        {
          eventId: 'evt-pulm-05',
          eventType: 'clinical.patient_routed.respiratory_hdu',
          stageName: 'Clinical Routing',
          timestamp: now - 3600000 * 0.4,
          actor: 'Dr. Farhan Qureshi, MD',
          summary: 'Patient routed to Respiratory HDU for monitored inpatient admission.',
        },
      ],
    };
  }
}
