import { EDOptimizedCase } from '@/lib/types/emergency';

export const INITIAL_ED_OPTIMIZED_CASES: EDOptimizedCase[] = [
  {
    id: 'er-opt-101',
    mrn: 'GH-2026-9812',
    patientName: 'Elena Rostova',
    age: 44,
    gender: 'Female',
    arrivalTime: '10:42 AM',
    arrivalMode: 'EMS_AMBULANCE',
    chiefComplaint: 'Sudden onset crushing retrosternal chest pain radiating to left jaw, diaphoresis',
    esiLevel: 1,
    assignedBay: 'Resus Bay 01 (Critical Care)',
    attendingPhysician: 'Dr. Sarah Jenkins',
    primaryNurse: 'Nurse John Davis, BSN',
    currentStage: 'TREATMENT',
    stageStatuses: {
      ARRIVAL: 'COMPLETED',
      TRIAGE: 'COMPLETED',
      ACUITY: 'COMPLETED',
      VITALS: 'COMPLETED',
      SBAR: 'COMPLETED',
      ORDERS: 'COMPLETED',
      DIAGNOSTICS: 'COMPLETED',
      TREATMENT: 'IN_PROGRESS',
      REASSESSMENT: 'PENDING',
      DISPOSITION: 'PENDING',
    },
    vitals: {
      hr: 118,
      bp: '88/54',
      spo2: 92,
      rr: 24,
      tempC: 36.6,
      gcs: 14,
      shockIndex: 1.34,
      mewsScore: 6,
    },
    criticalAlerts: {
      stemiAlert: true,
      strokeAlert: false,
      traumaAlphaAlert: false,
      sepsisAlert: false,
      codeBlueActive: false,
    },
    breakGlassActive: true,
    breakGlassReason: 'STAT STEMI / Hemodynamic instability: unconscious unconsented access to longitudinal allergy profile',
    breakGlassAuthorizedBy: 'Dr. Sarah Jenkins (Attending)',
    breakGlassTimestamp: '10:44 AM',
    emergencyBillingBypassed: true,
    emergencyBillingBypassReason: 'Life-saving emergent cardiac cath protocol bypasses upfront co-pay and financial pre-auth per EMTALA mandate',
    emergencyBillingBypassAuthorizedBy: 'Dr. Sarah Jenkins (Attending)',
    emergencyBillingBypassTimestamp: '10:44 AM',
    resuscitationInitiated: true,
    resuscitationTimestamp: '10:43 AM',
    sbar: {
      situation: '44F acute anterior STEMI with cardiogenic shock, BP 88/54.',
      background: 'Known CAD, previous PCI in 2024, hypertension, diabetic.',
      assessment: 'Impending cardiogenic shock secondary to LAD occlusion.',
      recommendation: 'Immediate Cath Lab activation for emergent primary PCI, Heparin bolus, Ticagrelor 180mg.',
      handoffFromDoctor: 'Dr. Sarah Jenkins (ED Attending)',
      handoffToDoctor: 'Dr. Marcus Vance (Interventional Cardiology)',
      handoffTimestamp: '10:55 AM',
      handoffNotes: 'Cath Lab team scrubbed in suite 2; patient pre-medicated with ASA 325mg and Heparin 5000U IV.',
    },
    statOrders: [
      {
        id: 'ord-st-1',
        type: 'MEDICATION',
        description: 'Aspirin 325 mg PO chewable STAT',
        orderedAt: '10:43 AM',
        orderedBy: 'Dr. Sarah Jenkins',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '10:44 AM',
      },
      {
        id: 'ord-st-2',
        type: 'MEDICATION',
        description: 'Unfractionated Heparin 5,000 units IV push STAT',
        orderedAt: '10:45 AM',
        orderedBy: 'Dr. Sarah Jenkins',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '10:46 AM',
      },
      {
        id: 'ord-st-3',
        type: 'MEDICATION',
        description: 'Ticagrelor 180 mg PO STAT loading dose',
        orderedAt: '10:48 AM',
        orderedBy: 'Dr. Sarah Jenkins',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '10:50 AM',
      },
      {
        id: 'ord-st-4',
        type: 'FLUID',
        description: 'Normal Saline 0.9% 500 mL IV bolus over 15 min for hypotension',
        orderedAt: '10:49 AM',
        orderedBy: 'Dr. Sarah Jenkins',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '10:52 AM',
      },
    ],
    diagnostics: [
      {
        id: 'diag-1',
        name: '12-Lead Electrocardiogram (ECG)',
        category: 'POCT',
        orderedAt: '10:42 AM',
        resultedAt: '10:44 AM',
        status: 'CRITICAL',
        resultSummary: 'Marked 4mm ST elevations in Leads V1-V4 with reciprocal depressions in II, III, aVF (Acute Anterior STEMI)',
        criticalNotifiedPhysician: 'Dr. Sarah Jenkins',
      },
      {
        id: 'diag-2',
        name: 'High-Sensitivity Troponin I (STAT POCT)',
        category: 'POCT',
        orderedAt: '10:43 AM',
        resultedAt: '10:51 AM',
        status: 'CRITICAL',
        resultSummary: '1,420 ng/L (Ref < 14 ng/L) - Highly Elevated',
        criticalNotifiedPhysician: 'Dr. Sarah Jenkins',
      },
      {
        id: 'diag-3',
        name: 'Arterial Blood Gas (ABG STAT)',
        category: 'POCT',
        orderedAt: '10:45 AM',
        resultedAt: '10:50 AM',
        status: 'CRITICAL',
        resultSummary: 'pH 7.31, pCO2 34, pO2 68, Lactate 3.8 mmol/L (Tissue Hypoperfusion)',
        criticalNotifiedPhysician: 'Dr. Sarah Jenkins',
      },
    ],
    treatments: [
      {
        id: 'tx-1',
        action: 'High-flow O2 via non-rebreather mask at 15 L/min',
        timestamp: '10:43 AM',
        performedBy: 'Nurse John Davis',
        outcome: 'SpO2 increased from 88% to 94%',
      },
      {
        id: 'tx-2',
        action: 'Dual large-bore 16G peripheral IV access established',
        timestamp: '10:44 AM',
        performedBy: 'Nurse Maya Patel',
        outcome: 'Bilateral antecubital lines patent, blood drawn for type & cross',
      },
      {
        id: 'tx-3',
        action: 'Defibrillator pads applied in anterior-posterior position',
        timestamp: '10:45 AM',
        performedBy: 'Nurse John Davis',
        outcome: 'Zoll X Series synchronized monitor active, rhythm tracked',
      },
    ],
    reassessments: [
      {
        id: 're-1',
        timestamp: '10:54 AM',
        clinician: 'Dr. Sarah Jenkins',
        vitalsSummary: 'BP 96/60, HR 104, SpO2 96% on 15L NRB, GCS 15',
        gcs: 15,
        painScore: 7,
        clinicalImpression: 'Borderline hemodynamics improved post-fluid bolus. Cath lab team notified, ready for immediate transfer.',
      },
    ],
    disposition: {
      type: 'EMERGENCY_OR',
      destinationBedOrFacility: 'Cardiac Catheterization Suite 2',
      authorizedBy: 'Dr. Sarah Jenkins',
      decidedAt: '10:56 AM',
      transportMode: 'Advanced Life Support Emergency Bed Escort',
    },
  },
  {
    id: 'er-opt-102',
    mrn: 'GH-2026-3108',
    patientName: 'Zubair Ahmed',
    age: 26,
    gender: 'Male',
    arrivalTime: '11:15 AM',
    arrivalMode: 'EMS_AMBULANCE',
    chiefComplaint: 'Motorcycle collision at 55 mph vs guardrail, severe left flank pain, rigid abdomen',
    esiLevel: 1,
    assignedBay: 'Trauma Bay 01',
    attendingPhysician: 'Dr. David Rodriguez',
    primaryNurse: 'Nurse Kevin O\'Connor, RN',
    currentStage: 'DIAGNOSTICS',
    stageStatuses: {
      ARRIVAL: 'COMPLETED',
      TRIAGE: 'COMPLETED',
      ACUITY: 'COMPLETED',
      VITALS: 'COMPLETED',
      SBAR: 'COMPLETED',
      ORDERS: 'COMPLETED',
      DIAGNOSTICS: 'IN_PROGRESS',
      TREATMENT: 'PENDING',
      REASSESSMENT: 'PENDING',
      DISPOSITION: 'PENDING',
    },
    vitals: {
      hr: 128,
      bp: '92/58',
      spo2: 95,
      rr: 28,
      tempC: 36.1,
      gcs: 13,
      shockIndex: 1.39,
      mewsScore: 7,
    },
    criticalAlerts: {
      stemiAlert: false,
      strokeAlert: false,
      traumaAlphaAlert: true,
      sepsisAlert: false,
      codeBlueActive: false,
    },
    breakGlassActive: true,
    breakGlassReason: 'Unidentified unconscious trauma victim: Break-glass authorization to query regional blood bank registry',
    breakGlassAuthorizedBy: 'Dr. David Rodriguez (Trauma Captain)',
    breakGlassTimestamp: '11:16 AM',
    emergencyBillingBypassed: true,
    emergencyBillingBypassReason: 'Trauma Alpha resuscitation bypasses registration desk & insurance verification',
    emergencyBillingBypassAuthorizedBy: 'Dr. David Rodriguez (Trauma Captain)',
    emergencyBillingBypassTimestamp: '11:16 AM',
    resuscitationInitiated: true,
    resuscitationTimestamp: '11:15 AM',
    sbar: {
      situation: '26M polytrauma status-post motorcycle crash, hypotensive, abdominal guarding.',
      background: 'No prior medical history obtainable from scene.',
      assessment: 'Grade IV splenic laceration with hemoperitoneum vs pelvic fracture.',
      recommendation: 'Massive Transfusion Protocol Pack 1, emergent portable FAST exam, Trauma Surgery STAT call.',
      handoffFromDoctor: 'Dr. David Rodriguez (Trauma Captain)',
      handoffToDoctor: 'Dr. Kamran Baig (Attending Trauma Surgeon)',
      handoffTimestamp: '11:22 AM',
      handoffNotes: 'Trauma Surgery activated in OR 4; blood uncrossed O-negative running.',
    },
    statOrders: [
      {
        id: 'ord-trauma-1',
        type: 'BLOOD',
        description: 'Emergency Release 2 Units O-Negative Uncrossmatched Packed Red Cells',
        orderedAt: '11:16 AM',
        orderedBy: 'Dr. David Rodriguez',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '11:20 AM',
      },
      {
        id: 'ord-trauma-2',
        type: 'MEDICATION',
        description: 'Tranexamic Acid (TXA) 1g IV in 100mL NS over 10 minutes',
        orderedAt: '11:17 AM',
        orderedBy: 'Dr. David Rodriguez',
        priority: 'STAT',
        status: 'ADMINISTERED',
        administeredAt: '11:21 AM',
      },
    ],
    diagnostics: [
      {
        id: 'diag-fast',
        name: 'Focused Assessment with Sonography in Trauma (FAST Ultrasound)',
        category: 'POCT',
        orderedAt: '11:16 AM',
        resultedAt: '11:19 AM',
        status: 'CRITICAL',
        resultSummary: 'Positive free fluid in Splenorenal fossa and Morrison pouch (Hemoperitoneum)',
        criticalNotifiedPhysician: 'Dr. David Rodriguez',
      },
    ],
    treatments: [
      {
        id: 'tx-pelvic',
        action: 'Pelvic circumferential compression binder applied at greater trochanters',
        timestamp: '11:17 AM',
        performedBy: 'Dr. David Rodriguez',
        outcome: 'Pelvic ring stabilized, no step-off deformity',
      },
    ],
    reassessments: [],
  },
  {
    id: 'er-opt-103',
    mrn: 'GH-2026-4421',
    patientName: 'Aisha Bello',
    age: 58,
    gender: 'Female',
    arrivalTime: '11:20 AM',
    arrivalMode: 'EMS_AMBULANCE',
    chiefComplaint: 'Acute right-sided hemiparesis and expressive aphasia, onset 45 minutes ago',
    esiLevel: 1,
    assignedBay: 'Stroke Resus Bay 02',
    attendingPhysician: 'Dr. Michael Chen',
    primaryNurse: 'Nurse Clara Oswald, RN',
    currentStage: 'DIAGNOSTICS',
    stageStatuses: {
      ARRIVAL: 'COMPLETED',
      TRIAGE: 'COMPLETED',
      ACUITY: 'COMPLETED',
      VITALS: 'COMPLETED',
      SBAR: 'COMPLETED',
      ORDERS: 'COMPLETED',
      DIAGNOSTICS: 'IN_PROGRESS',
      TREATMENT: 'PENDING',
      REASSESSMENT: 'PENDING',
      DISPOSITION: 'PENDING',
    },
    vitals: {
      hr: 88,
      bp: '172/96',
      spo2: 98,
      rr: 16,
      tempC: 36.8,
      gcs: 12,
      shockIndex: 0.51,
      mewsScore: 3,
    },
    criticalAlerts: {
      stemiAlert: false,
      strokeAlert: true,
      traumaAlphaAlert: false,
      sepsisAlert: false,
      codeBlueActive: false,
    },
    breakGlassActive: true,
    breakGlassReason: 'Acute Ischemic Stroke window: Break-glass access to medication history to confirm anticoagulation status',
    breakGlassAuthorizedBy: 'Dr. Michael Chen (Attending)',
    breakGlassTimestamp: '11:22 AM',
    emergencyBillingBypassed: true,
    emergencyBillingBypassReason: 'Code Stroke Door-to-Needle protocol bypasses financial clearance',
    emergencyBillingBypassAuthorizedBy: 'Dr. Michael Chen (Attending)',
    emergencyBillingBypassTimestamp: '11:22 AM',
    resuscitationInitiated: true,
    resuscitationTimestamp: '11:21 AM',
    sbar: {
      situation: '58F sudden right hemiplegia and global aphasia, LKW (Last Known Well) 10:35 AM.',
      background: 'Hypertension, Atrial Fibrillation (non-compliant with Eliquis).',
      assessment: 'Acute left MCA territory ischemic stroke, NIHSS 18.',
      recommendation: 'STAT non-contrast head CT + CT Angiography of head and neck, evaluate for Tenecteplase (TNK).',
    },
    statOrders: [
      {
        id: 'ord-stroke-1',
        type: 'IMAGING',
        description: 'STAT Non-Contrast Brain CT + CT Perfusion + CTA Head/Neck',
        orderedAt: '11:22 AM',
        orderedBy: 'Dr. Michael Chen',
        priority: 'STAT',
        status: 'ORDERED',
      },
    ],
    diagnostics: [
      {
        id: 'diag-ct-stroke',
        name: 'Rapid POCT Glucose & Fingerstick INR',
        category: 'POCT',
        orderedAt: '11:21 AM',
        resultedAt: '11:23 AM',
        status: 'NORMAL',
        resultSummary: 'Glucose 114 mg/dL (rules out hypoglycemia), INR 1.1',
      },
    ],
    treatments: [],
    reassessments: [],
  },
];
