import {
  DiseaseIntakeTemplate,
  LocalizationConfig,
  HospitalTierConfig,
} from '@/lib/types/disease-intake';

export const LOCALIZATION_CONFIGS: LocalizationConfig[] = [
  {
    id: 'us_aha_nih',
    name: 'United States (AHA / ACC / NIH / ACOG)',
    flagEmoji: '🇺🇸',
    guidelineAgency: 'AHA / ACC / ACEP / ACOG',
    triageSystem: 'ESI 1-5 (Emergency Severity Index)',
    units: {
      glucose: 'mg/dL',
      temperature: '°F',
      weight: 'lbs',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'Code STEMI (Door-to-Balloon < 90m)',
      stroke: 'Code Stroke (tPA / LVO Endovascular)',
      trauma: 'Level 1 Trauma Activation',
      obstetric: 'Code Stork / OB Hemorrhage Alert',
    },
    notes: 'Enforces US FDA/AHA acute timing windows, CMS quality metrics, and ICD-10-CM coding.',
  },
  {
    id: 'eu_esc_eso',
    name: 'European Union (ESC / ESO / ERC)',
    flagEmoji: '🇪🇺',
    guidelineAgency: 'European Society of Cardiology / ESO',
    triageSystem: 'MTS (Manchester Triage System)',
    units: {
      glucose: 'mmol/L',
      temperature: '°C',
      weight: 'kg',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'ESC 0/1h High-Sensitivity Troponin Protocol',
      stroke: 'ESO Thrombectomy Fast-Track',
      trauma: 'Polytrauma Shock Room Call',
      obstetric: 'Maternal Resuscitation Alert',
    },
    notes: 'Utilizes 0/1h and 0/2h rapid hs-cTn rule-in/rule-out algorithms and SI metric units.',
  },
  {
    id: 'uk_nice_nhs',
    name: 'United Kingdom (NICE / NHS Pathways)',
    flagEmoji: '🇬🇧',
    guidelineAgency: 'NICE Guidelines / Royal Colleges',
    triageSystem: 'NEWS2 (National Early Warning Score 2)',
    units: {
      glucose: 'mmol/L',
      temperature: '°C',
      weight: 'kg',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'PPCI Direct Access Pathway',
      stroke: 'HASU Hyper-Acute Stroke Unit Admission',
      trauma: 'Major Trauma Centre (MTC) Call',
      obstetric: 'Obstetric Emergency Call 2222',
    },
    notes: 'Standardized on NEWS2 physiological scoring triggers and NHS clinical governance pathways.',
  },
  {
    id: 'in_icmr',
    name: 'India & South Asia (ICMR / AIIMS Protocol)',
    flagEmoji: '🇮🇳',
    guidelineAgency: 'ICMR / Cardiological Society of India',
    triageSystem: 'AIIMS Triage Category (Red/Yellow/Green)',
    units: {
      glucose: 'mg/dL',
      temperature: '°F',
      weight: 'kg',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'STEMI India Pharmacoinvasive / PPCI Alert',
      stroke: 'Stroke Alert AIIMS Protocol',
      trauma: 'Golden Hour Red Trauma Alert',
      obstetric: 'Maternal High-Risk Emergency Alert',
    },
    notes: 'Incorporates high young-onset CAD prevalence, pharmacoinvasive thrombolysis fallback, and tropical disease screens.',
  },
  {
    id: 'gulf_doh_moh',
    name: 'Middle East & Gulf (DOH / DHA / Saudi MOH)',
    flagEmoji: '🇦🇪',
    guidelineAgency: 'DOH Abu Dhabi / Saudi MOH Protocols',
    triageSystem: 'CTAS / ESI Hybrid Triage',
    units: {
      glucose: 'mmol/L',
      temperature: '°C',
      weight: 'kg',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'Code Heart / Cath-Lab Stat Alert',
      stroke: 'Comprehensive Stroke Center Alert',
      trauma: 'Major Trauma Protocol Activation',
      obstetric: 'Code Pink / Obstetric Red Alert',
    },
    notes: 'Configured for high metabolic syndrome/diabetic foot presentation risk and JCI accreditation standards.',
  },
  {
    id: 'who_global',
    name: 'WHO Global Emergency Care Framework',
    flagEmoji: '🌐',
    guidelineAgency: 'World Health Organization (WHO BEC)',
    triageSystem: 'Interagency Integrated Triage (IIRT)',
    units: {
      glucose: 'mg/dL',
      temperature: '°C',
      weight: 'kg',
      pressure: 'mmHg',
    },
    emergencyCodeLabels: {
      cardiac: 'Acute Chest Pain Resuscitation Pathway',
      stroke: 'Acute Neuro Deficit Urgent Pathway',
      trauma: 'Advanced Trauma Resuscitation Protocol',
      obstetric: 'Emergency Obstetric and Newborn Care (EmONC)',
    },
    notes: 'Universal syndromic triage with low-resource redundancy safeguards.',
  },
];

export const HOSPITAL_TIER_CONFIGS: HospitalTierConfig[] = [
  {
    id: 'tier_quaternary',
    name: 'Quaternary Academic Medical Center',
    tierLevel: 'quaternary',
    cathLabAvailable: true,
    thrombectomyAvailable: true,
    pediatricIcuAvailable: true,
    bloodBankTier: 'Full Massive Transfusion',
    specialistEscalationTime: '< 10 minutes (On-Site Specialist)',
  },
  {
    id: 'tier_trauma_1',
    name: 'Level 1 Trauma & Comprehensive Stroke Center',
    tierLevel: 'trauma_1',
    cathLabAvailable: true,
    thrombectomyAvailable: true,
    pediatricIcuAvailable: true,
    bloodBankTier: 'Full Massive Transfusion',
    specialistEscalationTime: '< 15 minutes (24/7 Dedicated Teams)',
  },
  {
    id: 'tier_community',
    name: 'Community General Hospital',
    tierLevel: 'community',
    cathLabAvailable: true,
    thrombectomyAvailable: false,
    pediatricIcuAvailable: false,
    bloodBankTier: 'Standard Crossmatch',
    specialistEscalationTime: '< 30 minutes (On-Call Specialist / Tele-consult)',
  },
  {
    id: 'tier_ambulatory',
    name: 'Ambulatory Emergency & Urgent Care Center',
    tierLevel: 'ambulatory',
    cathLabAvailable: false,
    thrombectomyAvailable: false,
    pediatricIcuAvailable: false,
    bloodBankTier: 'Emergency O-Neg Only',
    specialistEscalationTime: 'Rapid EMS Transfer / Critical Transport Referral',
  },
];

export const INTAKE_TEMPLATES: DiseaseIntakeTemplate[] = [
  // 1. CARDIAC INTAKE
  {
    id: 'cardiac',
    name: 'Cardiac & Acute Coronary Syndrome Intake',
    specialty: 'Cardiology & Emergency Interventions',
    badge: 'Code STEMI & ACS Protocol',
    colorScheme: {
      primary: 'rose',
      lightBg: 'bg-rose-50',
      darkBg: 'dark:bg-rose-950/40',
      border: 'border-rose-200 dark:border-rose-800',
      accent: 'text-rose-600 dark:text-rose-400',
    },
    description:
      'Standardized acute chest discomfort, ischemia risk stratification (HEART / TIMI), 12-lead ECG telemetry routing, and door-to-balloon cath lab activation.',
    clinicalGuidelines: 'AHA/ACC 2023 ACS Guidelines & ESC 0/1-hour hs-cTn Algorithm',
    typicalSpecialists: ['Interventional Cardiologist', 'Cardiac Electrophysiologist', 'CCU Intensivist'],
    symptomTree: {
      id: 'cardiac_root',
      label: 'Acute Chest Discomfort / Ischemia Presentation',
      description: 'Patient reports chest or cardiovascular symptoms within last 24-48 hours',
      riskWeight: 4,
      children: [
        {
          id: 'cardiac_crushing',
          label: 'Retrosternal Crushing Pressure / Squeezing',
          description: 'Classic ischemic visceral chest pain with substernal heavy tightness',
          riskWeight: 8,
          isRedFlag: true,
          alertText: 'High probability of Acute Coronary Syndrome (ACS). Stat ECG required within 10 min.',
          children: [
            {
              id: 'cardiac_radiating_arm_jaw',
              label: 'Radiation to Left Arm, Neck, or Jaw',
              description: 'Pain radiating bilaterally or to left shoulder/arm/mandible',
              riskWeight: 9,
              isRedFlag: true,
              alertText: 'Strong positive likelihood ratio for acute myocardial infarction.',
            },
            {
              id: 'cardiac_diaphoresis_dyspnea',
              label: 'Associated Diaphoresis & Severe Dyspnea',
              description: 'Profuse cold sweating, shortness of breath, or presyncope',
              riskWeight: 9,
              isRedFlag: true,
              alertText: 'Indicates autonomic surge & impending hemodynamic instability.',
            },
            {
              id: 'cardiac_unresponsive_nitrates',
              label: 'Pain > 20 Mins / Unrelieved by Sublingual Nitroglycerin',
              description: 'Ongoing persistent ischemia without relief from rest or vasodilators',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'CRITICAL: Persistent transmural ischemia. Prepare for emergent Cath Lab activation.',
            },
          ],
        },
        {
          id: 'cardiac_sharp_tearing',
          label: 'Sudden "Tearing" Pain Radiating to Back / Scapula',
          description: 'Maximal intensity at onset, sharp migratory sensation between scapulae',
          riskWeight: 10,
          isRedFlag: true,
          alertText: 'HIGH RISK: Suspect Acute Aortic Dissection. Check bilateral BP differential; Avoid anticoagulation before CT.',
          children: [
            {
              id: 'cardiac_bp_differential',
              label: 'Pulse Deficit / > 20 mmHg Systolic BP Difference Between Arms',
              description: 'Asymmetric peripheral pulses or subclavian branch compromise',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'CRITICAL: High suspicion of Stanford Type A Aortic Dissection. Stat CTA Chest/Abdomen.',
            },
          ],
        },
        {
          id: 'cardiac_atypical',
          label: 'Atypical Equivalent (Dyspnea, Epigastric Burning, Fatigue in Diabetic/Elderly)',
          description: 'Painless ischemia, extreme exhaustion, unexplained nausea/vomiting',
          riskWeight: 6,
          children: [
            {
              id: 'cardiac_silent_diabetic',
              label: 'Known Diabetic Autonomic Neuropathy / Post-Menopausal Female',
              description: 'High risk of silent myocardial infarction without classic retrosternal pain',
              riskWeight: 7,
            },
          ],
        },
      ],
    },
    guidedQuestions: [
      {
        id: 'chest_pain_severity',
        label: 'Pain Severity Score (1 - 10 Numeric Rating Scale)',
        category: 'severity',
        type: 'scale',
        min: 1,
        max: 10,
        defaultValue: 8,
        required: true,
        helperText: 'Scale from 1 (mild) to 10 (most agonizing crushing pressure ever experienced).',
      },
      {
        id: 'symptom_onset_duration',
        label: 'Time Since Onset of Current Symptom Episode',
        category: 'timeline',
        type: 'select',
        required: true,
        options: [
          { value: 'under_2h', label: '< 2 Hours (Golden Window for Revascularization)', riskScore: 9, isRedFlag: true, alertMessage: 'Hyperacute window: door-to-balloon target is < 90 mins.' },
          { value: '2_to_6h', label: '2 to 6 Hours (Acute Ischemia)', riskScore: 8 },
          { value: '6_to_12h', label: '6 to 12 Hours (Evolving Infarction)', riskScore: 7 },
          { value: 'over_12h', label: '> 12 Hours (Subacute / Completed Infarction)', riskScore: 5 },
        ],
      },
      {
        id: 'ecg_telemetry_findings',
        label: 'Initial 12-Lead ECG Finding (Acquired within 10 mins)',
        category: 'examination',
        type: 'select',
        required: true,
        options: [
          { value: 'stemi_elevation', label: 'ST-Elevation ≥ 1mm in ≥ 2 Contiguous Leads (or New LBBB)', riskScore: 10, isRedFlag: true, alertMessage: 'CODE STEMI ACTIVATED: Notify Interventional Cardiologist & Cath Lab On-Call Team immediately.' },
          { value: 'st_depression_t_wave', label: 'ST-Depression ≥ 0.5mm or Deep T-Wave Inversions', riskScore: 8, alertMessage: 'High-Risk NSTE-ACS: Urgent heparinization & serial troponin monitoring.' },
          { value: 'arrhythmia_vt_vf', label: 'Ventricular Tachycardia / VFib / High-Grade AV Block', riskScore: 10, isRedFlag: true, alertMessage: 'CRITICAL ARRHYTHMIA: Charge Defibrillator, prepare Amiodarone/Cardioversion.' },
          { value: 'non_diagnostic', label: 'Non-Diagnostic / Normal Baseline ECG', riskScore: 3, helperText: 'Does not rule out NSTEMI; proceed with serial high-sensitivity troponin.' },
        ],
      },
      {
        id: 'associated_hemodynamic_signs',
        label: 'Associated Hemodynamic & Clinical Signs',
        category: 'associated_signs',
        type: 'multiselect',
        options: [
          { value: 'hypotension', label: 'Hypotension (Systolic BP < 90 mmHg / MAP < 65)', riskScore: 8, isRedFlag: true, alertMessage: 'Cardiogenic shock risk: Avoid nitrates/beta-blockers; prepare inotropes/ECHO.' },
          { value: 'pulmonary_edema', label: 'Bibasilar Crackles / Pulmonary Edema (Killip Class II-III)', riskScore: 7 },
          { value: 'syncope', label: 'Pre-Syncope or Transient Loss of Consciousness', riskScore: 6 },
          { value: 'levine_sign', label: 'Positive Levine Sign (Clenched fist held over sternum)', riskScore: 5 },
        ],
      },
    ],
    riskSignals: [
      {
        id: 'signal_code_stemi',
        title: 'CODE STEMI / Transmural Infarction Alert',
        severity: 'CRITICAL',
        triggerDescription: 'ST-segment elevation in ≥ 2 leads or new LBBB with ischemic symptoms < 12 hours',
        guidelineReference: 'ACC/AHA Class I Revascularization Recommendation',
        immediateAction: 'Page On-Call Interventional Cardiology Team; Mobilize Cath Lab Suite; Administer Aspirin 324mg chewable + P2Y12 inhibitor loading dose.',
        badgeColor: 'bg-rose-600 text-white',
        conditionChecker: (answers) => answers['ecg_telemetry_findings'] === 'stemi_elevation',
      },
      {
        id: 'signal_cardiogenic_shock',
        title: 'Impending Cardiogenic Shock Warning',
        severity: 'CRITICAL',
        triggerDescription: 'Ischemic symptoms accompanied by hypotension (SBP < 90 mmHg) and pulmonary rales',
        guidelineReference: 'SCAI Shock Classification Stage B/C',
        immediateAction: 'Avoid Nitrates, ACE-Inhibitors and Beta-Blockers. Order STAT Bedside Echo and prepare Norepinephrine / Dobutamine infusion.',
        badgeColor: 'bg-amber-600 text-white',
        conditionChecker: (answers) => Array.isArray(answers['associated_hemodynamic_signs']) && answers['associated_hemodynamic_signs'].includes('hypotension'),
      },
      {
        id: 'signal_high_heart_score',
        title: 'High-Risk Acute Coronary Syndrome (HEART Score > 7)',
        severity: 'HIGH',
        triggerDescription: 'Severe crushing pain + ST changes or multiple cardiovascular risk factors',
        guidelineReference: 'AHA/ACC Chest Pain Guideline 2021',
        immediateAction: 'Initiate continuous telemetry, IV Anticoagulation (Heparin / Enoxaparin), High-intensity Statin, and Cardiology consultation.',
        badgeColor: 'bg-orange-500 text-white',
        conditionChecker: (answers, history) => answers['chest_pain_severity'] >= 7 && (answers['ecg_telemetry_findings'] === 'st_depression_t_wave' || history['prior_pci_cabg'] === 'yes'),
      },
    ],
    specialtyHistory: [
      {
        id: 'cardiac_revasc_history',
        title: 'Cardiovascular Intervention & Structural History',
        description: 'Prior stents, surgical bypass grafts, and ejection fraction history',
        fields: [
          {
            key: 'prior_pci_cabg',
            label: 'Prior Coronary Intervention (PCI / CABG)',
            type: 'select',
            options: ['None', 'PCI with Drug-Eluting Stents (< 12 months)', 'PCI (> 12 months ago)', 'CABG Bypass Surgery (LIMA/Saphenous)'],
            defaultValue: 'None',
            clinicalImpact: 'Recent stents (< 12 mo) dramatically increase stent thrombosis risk if DAPT interrupted.',
          },
          {
            key: 'baseline_ef',
            label: 'Baseline Left Ventricular Ejection Fraction (LVEF %)',
            type: 'select',
            options: ['Preserved (> 50%)', 'Mildly Reduced (40-49%)', 'Moderately Reduced (30-39%)', 'Severely Reduced (< 30%)', 'Unknown / Never Tested'],
            defaultValue: 'Preserved (> 50%)',
          },
          {
            key: 'antiplatelet_regimen',
            label: 'Current Antiplatelet & Anticoagulant Regimen',
            type: 'multiselect',
            options: ['Aspirin 81mg Daily', 'Clopidogrel (Plavix) 75mg', 'Ticagrelor (Brilinta) 90mg BID', 'Prasugrel (Effient)', 'DOAC (Apixaban / Rivaroxaban)', 'Warfarin (Coumadin)'],
          },
          {
            key: 'known_cad_risk_factors',
            label: 'Established Atherosclerotic Risk Factors',
            type: 'multiselect',
            options: ['Type 2 Diabetes Mellitus', 'Hypertension', 'Hyperlipidemia', 'Active Tobacco Smoking', 'Family History Premature CAD (< 55m / < 65f)', 'Chronic Kidney Disease (CKD)'],
          },
        ],
      },
    ],
  },

  // 2. STROKE INTAKE
  {
    id: 'stroke',
    name: 'Acute Stroke & Large Vessel Occlusion Intake',
    specialty: 'Neurology & Neuro-Interventional Surgery',
    badge: 'Code Stroke & LVO Protocol',
    colorScheme: {
      primary: 'purple',
      lightBg: 'bg-purple-50',
      darkBg: 'dark:bg-purple-950/40',
      border: 'border-purple-200 dark:border-purple-800',
      accent: 'text-purple-600 dark:text-purple-400',
    },
    description:
      'Standardized acute focal neurological deficit intake, Last Known Well (LKW) countdown, BE-FAST scale, NIHSS triage, tPA thrombolysis eligibility, and CTA/CTP thrombectomy screening.',
    clinicalGuidelines: 'AHA/ASA 2023 Acute Ischemic Stroke Guidelines & ESO Thrombectomy Standards',
    typicalSpecialists: ['Vascular Neurologist', 'Neuro-Interventional Radiologist', 'Neuro-Intensivist'],
    symptomTree: {
      id: 'stroke_root',
      label: 'Acute Neurological Deficit / Loss of Function',
      description: 'Sudden onset of focal brain or cranial nerve dysfunction',
      riskWeight: 5,
      children: [
        {
          id: 'stroke_anterior_circ',
          label: 'Anterior Circulation / Hemispheric Deficit (MCA / ICA)',
          description: 'Unilateral arm/leg weakness, facial droop, speech impairment',
          riskWeight: 8,
          isRedFlag: true,
          children: [
            {
              id: 'stroke_severe_hemiparesis',
              label: 'Dense Unilateral Hemiplegia + Forced Conjugate Gaze Deviation',
              description: 'Eyes deviated toward lesion side with profound contralateral weakness',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'HIGH LVO PROBABILITY: MCA M1 or ICA Occlusion suspected. Stat CTA Head/Neck.',
            },
            {
              id: 'stroke_aphasia',
              label: 'Global or Expressive/Receptive Aphasia',
              description: 'Inability to comprehend language or produce fluent speech',
              riskWeight: 9,
              isRedFlag: true,
            },
            {
              id: 'stroke_neglect',
              label: 'Hemispatial Inattention / Severe Visuospatial Neglect',
              description: 'Ignores left-sided tactile, auditory, or visual stimuli (Non-dominant hemisphere)',
              riskWeight: 8,
            },
          ],
        },
        {
          id: 'stroke_posterior_circ',
          label: 'Posterior Circulation / Brainstem & Cerebellar Syndrome',
          description: 'Sudden vertigo, ataxia, crossed sensory loss, diplopia, dysmetria',
          riskWeight: 9,
          isRedFlag: true,
          alertText: 'Basilar Artery Occlusion is a life-threatening emergency. Assess airway and cranial nerves.',
          children: [
            {
              id: 'stroke_basilar_coma',
              label: 'Locked-In State / Decreased Level of Consciousness / Quadriparesis',
              description: 'Basilar tip syndrome with acute obtundation or bilateral motor weakness',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'EMERGENT BASILAR ARTERY THROMBOSIS: Immediate Neuro-Interventional consultation.',
            },
          ],
        },
        {
          id: 'stroke_transient_tia',
          label: 'Transient Neurological Deficit (Symptoms Resolving / TIA)',
          description: 'Focal symptoms lasted minutes to < 1 hour and completely resolved',
          riskWeight: 6,
          children: [
            {
              id: 'stroke_high_abcd2',
              label: 'ABCD2 Score > 4 (High 48-Hour Stroke Recurrence Risk)',
              description: 'Age ≥ 60, BP ≥ 140/90, Unilateral weakness, Duration ≥ 60 min, Diabetes',
              riskWeight: 7,
            },
          ],
        },
      ],
    },
    guidedQuestions: [
      {
        id: 'last_known_well_window',
        label: 'Exact Time Last Known Well (LKW)',
        category: 'timeline',
        type: 'select',
        required: true,
        options: [
          { value: 'under_3h', label: '< 3.0 Hours (Standard IV Thrombolysis Window)', riskScore: 10, isRedFlag: true, alertMessage: 'ELIGIBLE FOR IV THROMBOLYSIS (tPA/TNK): Door-to-Needle goal < 45 min.' },
          { value: '3_to_4_5h', label: '3.0 - 4.5 Hours (Extended IV Thrombolysis Window)', riskScore: 9, alertMessage: 'Check extended AHA/ASA exclusion criteria (Age > 80, Prior Stroke + DM, NIHSS > 25).' },
          { value: '4_5_to_24h', label: '4.5 - 24 Hours (Endovascular Thrombectomy / DAWN & DEFUSE-3 Window)', riskScore: 8, alertMessage: 'STAT CT Perfusion / MRI DWI-FLAIR to assess ischemic core vs penumbra volume.' },
          { value: 'wake_up_stroke', label: 'Wake-Up Stroke / Unknown Onset Time', riskScore: 7, alertMessage: 'Obtain MRI Brain with DWI-FLAIR mismatch or CT Perfusion mismatch.' },
          { value: 'over_24h', label: '> 24 Hours (Secondary Prevention & Rehabilitation)', riskScore: 4 },
        ],
      },
      {
        id: 'be_fast_screening',
        label: 'BE-FAST Stroke Scale Components Observed',
        category: 'primary_symptom',
        type: 'multiselect',
        required: true,
        options: [
          { value: 'balance', label: 'B - Balance (Sudden loss of balance, dizziness, ataxia)', riskScore: 2 },
          { value: 'eyes', label: 'E - Eyes (Sudden loss of vision in one or both eyes, hemianopia)', riskScore: 2 },
          { value: 'face', label: 'F - Face Drooping (Unequal smile, asymmetric nasolabial fold)', riskScore: 2, isRedFlag: true },
          { value: 'arm', label: 'A - Arm Weakness (Arm drift downward within 10 seconds)', riskScore: 3, isRedFlag: true },
          { value: 'speech', label: 'S - Speech Difficulty (Slurred speech, aphasia, unable to repeat sentences)', riskScore: 3, isRedFlag: true },
        ],
      },
      {
        id: 'rapid_blood_glucose',
        label: 'Point-of-Care Capillary Blood Glucose (r/o Hypoglycemia Mimic)',
        category: 'examination',
        type: 'number',
        unit: 'mg/dL',
        defaultValue: 118,
        required: true,
        helperText: 'Hypoglycemia (< 54 mg/dL) must be immediately corrected before diagnosing stroke.',
      },
      {
        id: 'estimated_nihss',
        label: 'Estimated Initial NIH Stroke Scale (NIHSS: 0 - 42)',
        category: 'severity',
        type: 'scale',
        min: 0,
        max: 42,
        defaultValue: 12,
        required: true,
        helperText: '0 = Normal, 1-4 = Minor stroke, 5-15 = Moderate stroke, 16-20 = Moderate/Severe, 21-42 = Severe stroke.',
      },
    ],
    riskSignals: [
      {
        id: 'signal_code_stroke_thrombolysis',
        title: 'CODE STROKE / IV Thrombolysis Golden Window',
        severity: 'CRITICAL',
        triggerDescription: 'Focal neurological deficit with Last Known Well < 4.5 hours and glucose > 60 mg/dL',
        guidelineReference: 'AHA/ASA 2023 Class I Recommendation',
        immediateAction: 'Transport direct to CT Scanner for Non-Contrast Brain CT + CTA Head/Neck. Verify INR, Platelets, and Anticoagulation history.',
        badgeColor: 'bg-purple-600 text-white',
        conditionChecker: (answers) => answers['last_known_well_window'] === 'under_3h' || answers['last_known_well_window'] === '3_to_4_5h',
      },
      {
        id: 'signal_lvo_thrombectomy',
        title: 'Large Vessel Occlusion (LVO) Van Alert',
        severity: 'CRITICAL',
        triggerDescription: 'NIHSS ≥ 6 with cortical signs (Gaze deviation, Aphasia, Neglect) or LKW < 24 hours',
        guidelineReference: 'DEFUSE-3 / DAWN Trial Guidelines',
        immediateAction: 'Page Neuro-Interventional Surgery Team for emergent mechanical thrombectomy suite activation.',
        badgeColor: 'bg-rose-600 text-white',
        conditionChecker: (answers) => Number(answers['estimated_nihss']) >= 6,
      },
      {
        id: 'signal_anticoagulation_contraindication',
        title: 'Anticoagulated Stroke Protocol Guardrail',
        severity: 'HIGH',
        triggerDescription: 'Patient takes active DOAC (within 48h) or Warfarin with INR > 1.7',
        guidelineReference: 'IV Thrombolysis Safety Exclusion Criteria',
        immediateAction: 'IV tPA contraindicated unless specific reversal agent given (Idarucizumab for Dabigatran / Andexanet Alfa). Prioritize mechanical thrombectomy.',
        badgeColor: 'bg-amber-600 text-white',
        conditionChecker: (_answers, history) => history['current_anticoagulant'] !== 'None' && history['current_anticoagulant'] !== undefined,
      },
    ],
    specialtyHistory: [
      {
        id: 'stroke_neuro_history',
        title: 'Neurological & Anticoagulation History',
        description: 'Baseline functional status, prior cerebrovascular events, and anticoagulants',
        fields: [
          {
            key: 'pre_morbid_mrs',
            label: 'Pre-Stroke Baseline Modified Rankin Scale (mRS 0-5)',
            type: 'select',
            options: ['0 - No symptoms at all', '1 - No significant disability (able to carry out all usual activities)', '2 - Slight disability (unable to carry out all previous activities but independent)', '3 - Moderate disability (requires some help but walks unassisted)', '4 - Moderately severe disability (unable to walk/attend to bodily needs without assistance)', '5 - Severe disability (bedridden, incontinent, requiring constant nursing)'],
            defaultValue: '0 - No symptoms at all',
            clinicalImpact: 'Pre-stroke mRS ≤ 2 qualifies for aggressive endovascular revascularization.',
          },
          {
            key: 'current_anticoagulant',
            label: 'Current Oral Anticoagulant Therapy',
            type: 'select',
            options: ['None', 'Apixaban (Eliquis) within 48 hours', 'Rivaroxaban (Xarelto) within 48 hours', 'Dabigatran (Pradaxa) within 48 hours', 'Warfarin (Coumadin) - Last INR Unknown', 'Warfarin (Coumadin) - Last INR > 1.7', 'Subcutaneous Heparin / Lovenox within 24 hours'],
            defaultValue: 'None',
          },
          {
            key: 'atrial_fibrillation_history',
            label: 'History of Atrial Fibrillation or Embolic Source',
            type: 'select',
            options: ['None', 'Paroxysmal Atrial Fibrillation', 'Persistent / Permanent Atrial Fibrillation', 'Mechanical Heart Valve', 'Severe Carotid Stenosis (> 70%)'],
            defaultValue: 'None',
          },
        ],
      },
    ],
  },

  // 3. DIABETIC INTAKE
  {
    id: 'diabetic',
    name: 'Diabetic Crisis & Metabolic Emergency Intake',
    specialty: 'Endocrinology & Critical Care Metabolism',
    badge: 'DKA & HHS Metabolic Protocol',
    colorScheme: {
      primary: 'amber',
      lightBg: 'bg-amber-50',
      darkBg: 'dark:bg-amber-950/40',
      border: 'border-amber-200 dark:border-amber-800',
      accent: 'text-amber-600 dark:text-amber-400',
    },
    description:
      'Structured intake for diabetic ketoacidosis (DKA), hyperosmolar hyperglycemic state (HHS), severe hypoglycemia, anion gap computation, and insulin infusion titration.',
    clinicalGuidelines: 'ADA 2024 Standards of Care & Endocrine Society DKA Consensus',
    typicalSpecialists: ['Endocrinologist', 'Critical Care Intensivist', 'Diabetic Nurse Educator'],
    symptomTree: {
      id: 'diabetic_root',
      label: 'Acute Glycemic & Metabolic Derangement',
      description: 'Severe hyperglycemia, ketone production, dehydration, or hypoglycemic neuroglycopenia',
      riskWeight: 4,
      children: [
        {
          id: 'diabetic_hyperglycemia_ketosis',
          label: 'Severe Hyperglycemia (> 300 mg/dL) with Ketosis / Acidosis',
          description: 'Nausea, vomiting, diffuse abdominal pain, polyuria, polydipsia',
          riskWeight: 8,
          isRedFlag: true,
          children: [
            {
              id: 'diabetic_kussmaul_breathing',
              label: 'Kussmaul Rapid Deep Respirations & Fruity Acetone Breath',
              description: 'Respiratory compensation for severe metabolic acidemia (Arterial pH < 7.20)',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'CRITICAL DKA: Severe acidemia. Check Potassium before starting IV Insulin!',
            },
            {
              id: 'diabetic_euglycemic_dka',
              label: 'Euglycemic DKA (Normal or mildly elevated glucose < 250 mg/dL on SGLT2-Inhibitors)',
              description: 'Profound ketoacidosis despite near-normal capillary glucose in patients on SGLT2i',
              riskWeight: 9,
              isRedFlag: true,
              alertText: 'SGLT2i-Induced Euglycemic DKA. Do not withhold IV dextrose with insulin infusion.',
            },
          ],
        },
        {
          id: 'diabetic_hhs',
          label: 'Hyperosmolar Hyperglycemic State (HHS / HONK)',
          description: 'Profound dehydration, glucose > 600 mg/dL, serum osmolality > 320 mOsm/kg, altered mental status',
          riskWeight: 9,
          isRedFlag: true,
          alertText: 'High mortality risk. Massive fluid deficit (8-12 Liters). Slower insulin titration required.',
          children: [
            {
              id: 'diabetic_hhs_coma',
              label: 'Coma / Severe Lethargy / Hyperviscosity Thrombosis Risk',
              description: 'GCS < 10, focal neurological signs, profound volume contraction',
              riskWeight: 10,
              isRedFlag: true,
            },
          ],
        },
        {
          id: 'diabetic_severe_hypo',
          label: 'Severe Hypoglycemia (< 54 mg/dL with Neuroglycopenia)',
          description: 'Confusion, diaphoresis, seizure, loss of consciousness, adrenergic storm',
          riskWeight: 9,
          isRedFlag: true,
          alertText: 'EMERGENCY: Immediate IV 50% Dextrose (D50W 25-50mL) or IM Glucagon.',
        },
      ],
    },
    guidedQuestions: [
      {
        id: 'point_of_care_glucose',
        label: 'Point-of-Care Capillary Glucose',
        category: 'severity',
        type: 'number',
        unit: 'mg/dL',
        defaultValue: 480,
        required: true,
        helperText: 'Readings > 500 mg/dL may display as "HIGH" on standard meters.',
      },
      {
        id: 'blood_beta_hydroxybutyrate',
        label: 'Blood Beta-Hydroxybutyrate (Serum Ketones)',
        category: 'examination',
        type: 'select',
        required: true,
        options: [
          { value: 'normal_under_0_6', label: '< 0.6 mmol/L (Normal / Negative Ketones)', riskScore: 1 },
          { value: 'mild_0_6_to_1_5', label: '0.6 - 1.5 mmol/L (Mild Ketonemia / Fasting Ketones)', riskScore: 4 },
          { value: 'moderate_1_5_to_3_0', label: '1.5 - 3.0 mmol/L (Moderate Ketonemia / Impending DKA)', riskScore: 7 },
          { value: 'severe_over_3_0', label: '> 3.0 mmol/L (Severe DKA / High Acidosis Risk)', riskScore: 10, isRedFlag: true, alertMessage: 'CRITICAL KETONEMIA: Indicates active ketoacidosis.' },
        ],
      },
      {
        id: 'serum_potassium_level',
        label: 'Serum Potassium (K+) Level Available',
        category: 'examination',
        type: 'select',
        required: true,
        options: [
          { value: 'hypokalemia_under_3_3', label: '< 3.3 mEq/L (HYPOKALEMIA - HOLD INSULIN INFUSION!)', riskScore: 10, isRedFlag: true, alertMessage: 'SAFETY WARNING: DO NOT START INSULIN! Administer IV Potassium replacement first to prevent fatal arrhythmia.' },
          { value: 'normal_3_3_to_5_3', label: '3.3 - 5.3 mEq/L (Normal - Start Insulin with IV KCl supplementation)', riskScore: 3 },
          { value: 'hyperkalemia_over_5_3', label: '> 5.3 mEq/L (Hyperkalemic - Start Insulin without Potassium)', riskScore: 5 },
          { value: 'pending_stat_lab', label: 'STAT Lab Pending (Results expected in < 15 min)', riskScore: 4 },
        ],
      },
      {
        id: 'mental_status_hydration',
        label: 'Consciousness & Hydration Assessment',
        category: 'associated_signs',
        type: 'select',
        options: [
          { value: 'alert_mild_dry', label: 'Alert & Oriented, Mild Mucosal Dryness', riskScore: 2 },
          { value: 'somnolent_moderate', label: 'Somnolent / Lethargic, Poor Skin Turgor, Tachycardia', riskScore: 6 },
          { value: 'stupor_severe_hhs', label: 'Stupor / Unresponsive, Hypotension, Sunken Eyes', riskScore: 9, isRedFlag: true },
        ],
      },
    ],
    riskSignals: [
      {
        id: 'signal_critical_dka',
        title: 'CRITICAL DKA (Severe Ketoacidosis) Protocol',
        severity: 'CRITICAL',
        triggerDescription: 'Glucose > 250 mg/dL + Ketones > 3.0 mmol/L or Kussmaul respirations',
        guidelineReference: 'ADA Standards of Care in Diabetes 2024',
        immediateAction: 'Initiate aggressive isotonic saline (1.0 - 1.5 L/hr), confirm K+ ≥ 3.3 mEq/L before starting regular insulin infusion at 0.1 units/kg/hr.',
        badgeColor: 'bg-rose-600 text-white',
        conditionChecker: (answers) => answers['blood_beta_hydroxybutyrate'] === 'severe_over_3_0',
      },
      {
        id: 'signal_hypokalemia_insulin_lock',
        title: 'FATAL HYPOKALEMIA GUARDRAIL: Insulin Withheld',
        severity: 'CRITICAL',
        triggerDescription: 'Potassium < 3.3 mEq/L detected during acute ketoacidosis intake',
        guidelineReference: 'Endocrine Society Clinical Practice Safety Rule',
        immediateAction: 'HOLD IV INSULIN. Infuse IV KCl 20-40 mEq/hr until serum K+ exceeds 3.3 mEq/L.',
        badgeColor: 'bg-red-700 text-white animate-pulse',
        conditionChecker: (answers) => answers['serum_potassium_level'] === 'hypokalemia_under_3_3',
      },
    ],
    specialtyHistory: [
      {
        id: 'diabetes_regimen_history',
        title: 'Diabetes Diagnosis, Regimen & Renal Profile',
        description: 'Diabetes classification, insulin delivery modalities, and baseline nephropathy',
        fields: [
          {
            key: 'diabetes_type',
            label: 'Diabetes Classification',
            type: 'select',
            options: ['Type 1 Diabetes Mellitus (T1DM)', 'Type 2 Diabetes Mellitus (T2DM)', 'Latent Autoimmune Diabetes in Adults (LADA)', 'Pancreatogenic (Type 3c)', 'Gestational Diabetes (GDM)'],
            defaultValue: 'Type 1 Diabetes Mellitus (T1DM)',
          },
          {
            key: 'insulin_modality',
            label: 'Insulin Delivery Modality',
            type: 'select',
            options: ['Multiple Daily Injections (MDI - Basal/Bolus)', 'Continuous Subcutaneous Insulin Infusion (CSII Pump)', 'Automated Closed-Loop Artificial Pancreas', 'Oral Antidiabetic Agents Only', 'Diet Controlled'],
            defaultValue: 'Multiple Daily Injections (MDI - Basal/Bolus)',
          },
          {
            key: 'sglt2_inhibitor_use',
            label: 'Active SGLT2-Inhibitor (e.g., Empagliflozin, Dapagliflozin)',
            type: 'select',
            options: ['No', 'Yes - Empagliflozin (Jardiance)', 'Yes - Dapagliflozin (Farxiga)', 'Yes - Canagliflozin (Invokana)'],
            defaultValue: 'No',
            clinicalImpact: 'High risk for Euglycemic DKA with minimal hyperglycemia.',
          },
          {
            key: 'baseline_renal_creatinine',
            label: 'Baseline Renal Function / eGFR',
            type: 'select',
            options: ['Normal (eGFR > 90 mL/min)', 'Mild CKD (eGFR 60-89)', 'Moderate CKD Stage 3 (eGFR 30-59)', 'Severe CKD Stage 4-5 (eGFR < 30)', 'End-Stage Renal Disease (ESRD on Hemodialysis)'],
            defaultValue: 'Normal (eGFR > 90 mL/min)',
          },
        ],
      },
    ],
  },

  // 4. ORTHOPEDIC TRAUMA INTAKE
  {
    id: 'ortho_trauma',
    name: 'Orthopedic Trauma & Limb Salvage Intake',
    specialty: 'Orthopedic Trauma Surgery & Musculoskeletal ER',
    badge: 'Trauma & Compartment Syndrome Protocol',
    colorScheme: {
      primary: 'emerald',
      lightBg: 'bg-emerald-50',
      darkBg: 'dark:bg-emerald-950/40',
      border: 'border-emerald-200 dark:border-emerald-800',
      accent: 'text-emerald-600 dark:text-emerald-400',
    },
    description:
      'High-energy skeletal trauma intake, Gustilo-Anderson open fracture grading, acute compartment syndrome tension scoring, neurovascular distal perfusion, and surgical debridement timing.',
    clinicalGuidelines: 'OTA / AAOS Open Fracture & Compartment Syndrome Clinical Guidelines',
    typicalSpecialists: ['Orthopedic Trauma Surgeon', 'Vascular Surgeon', 'Trauma Team Leader'],
    symptomTree: {
      id: 'ortho_root',
      label: 'Acute Musculoskeletal Trauma / Extremity Injury',
      description: 'Fracture, dislocation, crush, high-velocity blunt trauma or penetrating limb injury',
      riskWeight: 5,
      children: [
        {
          id: 'ortho_compartment_syndrome',
          label: 'Suspected Acute Compartment Syndrome (ACS)',
          description: 'Disproportionate agonizing pain, tense woody compartment, pain on passive stretch',
          riskWeight: 10,
          isRedFlag: true,
          alertText: 'SURGICAL EMERGENCY: Compartment pressure > 30 mmHg or delta pressure < 30 mmHg demands STAT Fasciotomy.',
          children: [
            {
              id: 'ortho_passive_stretch_pain',
              label: 'Severe Pain Exacerbated by Passive Stretch of Digits',
              description: 'Earliest and most sensitive clinical hallmark of muscle ischemia',
              riskWeight: 10,
              isRedFlag: true,
            },
            {
              id: 'ortho_woody_tenseness',
              label: 'Tense "Woody" Feeling of Muscular Compartment to Palpation',
              description: 'Loss of normal compliance in anterior/posterior fascial compartments',
              riskWeight: 9,
              isRedFlag: true,
            },
          ],
        },
        {
          id: 'ortho_open_fracture',
          label: 'Open Fracture (Bone Pierced Skin / Traumatic Wound)',
          description: 'Compound skeletal injury with bacterial exposure and soft-tissue envelope loss',
          riskWeight: 9,
          isRedFlag: true,
          alertText: 'Administer IV Antibiotics within 60 mins of arrival (Cefazolin +/- Gentamicin) + Tetanus toxoid.',
          children: [
            {
              id: 'ortho_gustilo_3c',
              label: 'Gustilo Type IIIC (Open Fracture with Major Arterial Injury Requiring Repair)',
              description: 'Loss of distal pulses, cold pulseless limb, active hemorrhage',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'CRITICAL LIMB THREAT: Simultaneous Orthopedic and Vascular surgical mobilization.',
            },
          ],
        },
        {
          id: 'ortho_closed_dislocation',
          label: 'Joint Dislocation with Neurovascular Entrapment',
          description: 'Knee, hip, or ankle dislocation with potential popliteal or sciatic compromise',
          riskWeight: 8,
          children: [
            {
              id: 'ortho_knee_dislocation',
              label: 'Knee (Tibiofemoral) Dislocation',
              description: 'Extremely high risk of popliteal artery intimal tear; Mandatory ABI or CT Angiogram',
              riskWeight: 9,
              isRedFlag: true,
            },
          ],
        },
      ],
    },
    guidedQuestions: [
      {
        id: 'mechanism_of_injury',
        label: 'Trauma Mechanism & Kinetic Energy',
        category: 'primary_symptom',
        type: 'select',
        required: true,
        options: [
          { value: 'high_speed_mvc', label: 'High-Speed Motor Vehicle Collision (> 45 mph / Rollover / Ejection)', riskScore: 9, isRedFlag: true },
          { value: 'pedestrian_struck', label: 'Pedestrian / Cyclist Struck by Auto', riskScore: 9, isRedFlag: true },
          { value: 'fall_from_height', label: 'Fall from Height (> 10 feet / 3 meters)', riskScore: 8 },
          { value: 'crush_industrial', label: 'Heavy Industrial Machinery Crush / Blast', riskScore: 10, isRedFlag: true },
          { value: 'ground_level_fall', label: 'Ground-Level Fall (Fragility / Elderly)', riskScore: 4 },
        ],
      },
      {
        id: 'gustilo_classification',
        label: 'Open Wound / Gustilo-Anderson Grade',
        category: 'severity',
        type: 'select',
        required: true,
        options: [
          { value: 'closed', label: 'Closed Injury (Intact skin envelope)', riskScore: 2 },
          { value: 'type_1', label: 'Type I: Clean open wound < 1 cm, minimal soft tissue damage', riskScore: 6 },
          { value: 'type_2', label: 'Type II: Laceration 1 - 10 cm without extensive soft tissue stripping', riskScore: 8 },
          { value: 'type_3a', label: 'Type IIIA: High energy > 10 cm, adequate periosteal coverage', riskScore: 9, isRedFlag: true },
          { value: 'type_3b', label: 'Type IIIB: Extensive periosteal stripping, requires flap reconstruction', riskScore: 9, isRedFlag: true },
          { value: 'type_3c', label: 'Type IIIC: Open fracture with major arterial disruption requiring repair', riskScore: 10, isRedFlag: true, alertMessage: 'STAT VASCULAR & ORTHO SURGERY ACTIVATION.' },
        ],
      },
      {
        id: 'distal_neurovascular_status',
        label: 'Distal Extremity Neurovascular Perfusion Status',
        category: 'examination',
        type: 'select',
        required: true,
        options: [
          { value: 'warm_palpable_pulses', label: 'Warm, Well-Perfused, 2+ Palpable Pulses (DP/PT/Radial), Sensation Intact', riskScore: 1 },
          { value: 'diminished_pulses', label: 'Diminished Pulses (1+), Cap Refill > 3s, Sensation Intact', riskScore: 6 },
          { value: 'pulseless_cold', label: 'PULSELESS, Pale/Cyanotic, Cold Extremity, Paresthesias', riskScore: 10, isRedFlag: true, alertMessage: 'CRITICAL ARTERIAL ISCHEMIA: Warm ischemia time > 6 hrs leads to irreversible muscle necrosis.' },
        ],
      },
      {
        id: 'compartment_cardinal_signs',
        label: 'Cardinal Signs of Compartment Syndrome (The 5 Ps)',
        category: 'associated_signs',
        type: 'multiselect',
        options: [
          { value: 'pain_disproportionate', label: 'Pain out of proportion to injury severity', riskScore: 3, isRedFlag: true },
          { value: 'passive_stretch', label: 'Agonizing pain on passive stretch of toe/finger flexors', riskScore: 4, isRedFlag: true },
          { value: 'paresthesia', label: 'Paresthesia / Numbness in nerve distribution (e.g. 1st webspace)', riskScore: 3 },
          { value: 'pressure_tense', label: 'Palpably tense, rock-hard "woody" compartment', riskScore: 3, isRedFlag: true },
          { value: 'paralysis', label: 'Paralysis / Motor deficit (Late sign)', riskScore: 4, isRedFlag: true },
        ],
      },
    ],
    riskSignals: [
      {
        id: 'signal_compartment_syndrome_fasciotomy',
        title: 'EMERGENT COMPARTMENT SYNDROME ALERT',
        severity: 'CRITICAL',
        triggerDescription: 'Pain out of proportion + agonizing passive stretch pain or tense compartment',
        guidelineReference: 'AAOS Emergency Surgical Standards',
        immediateAction: 'Remove all constrictive dressings/casts immediately to skin level. Measure compartment pressures (Stryker needle); Book Emergency OR for 2-incision 4-compartment fasciotomy.',
        badgeColor: 'bg-rose-600 text-white animate-pulse',
        conditionChecker: (answers) => Array.isArray(answers['compartment_cardinal_signs']) && (answers['compartment_cardinal_signs'].includes('passive_stretch') || answers['compartment_cardinal_signs'].includes('pain_disproportionate')),
      },
      {
        id: 'signal_open_fracture_abx',
        title: 'Open Fracture Infection Prevention Protocol',
        severity: 'HIGH',
        triggerDescription: 'Gustilo Type I-III open skeletal fracture',
        guidelineReference: 'Surgical Infection Society (SIS) Trauma Guidelines',
        immediateAction: 'Administer IV Cefazolin 2g (+ Gentamicin 5mg/kg if Type III). Administer Tetanus Toxoid 0.5 mL IM. Cover wound with sterile saline gauze (Do not probe or irrigate in ER).',
        badgeColor: 'bg-emerald-600 text-white',
        conditionChecker: (answers) => answers['gustilo_classification'] && answers['gustilo_classification'] !== 'closed',
      },
    ],
    specialtyHistory: [
      {
        id: 'ortho_patient_profile',
        title: 'Musculoskeletal Profile, Anticoagulation & Tetanus',
        description: 'Baseline functional status, anticoagulant agents, and tetanus immunity',
        fields: [
          {
            key: 'tetanus_immunization_status',
            label: 'Tetanus Toxoid Immunization Recency',
            type: 'select',
            options: ['Up to date (< 5 years ago)', 'Received 5 - 10 years ago', 'Unknown / > 10 years ago / Never vaccinated'],
            defaultValue: 'Up to date (< 5 years ago)',
          },
          {
            key: 'anticoagulation_bleeding_risk',
            label: 'Active Antithrombotic / Anticoagulant Therapy',
            type: 'select',
            options: ['None', 'Aspirin 81mg / Clopidogrel 75mg', 'DOAC (Eliquis / Xarelto)', 'Warfarin (Coumadin)', 'Heparin / LMWH'],
            defaultValue: 'None',
          },
          {
            key: 'pre_existing_ortho_hardware',
            label: 'Prior Hardware / Total Joint Arthroplasty in Injured Limb',
            type: 'select',
            options: ['None', 'Total Hip Arthroplasty (THA)', 'Total Knee Arthroplasty (TKA)', 'Prior Intramedullary Nail / ORIF Plate'],
            defaultValue: 'None',
          },
        ],
      },
    ],
  },

  // 5. OB/GYN INTAKE
  {
    id: 'obgyn',
    name: 'Obstetric Emergency & Preeclampsia Intake',
    specialty: 'Obstetrics, Maternal-Fetal Medicine & Labor ER',
    badge: 'Code Stork & Hypertensive Crisis',
    colorScheme: {
      primary: 'teal',
      lightBg: 'bg-teal-50',
      darkBg: 'dark:bg-teal-950/40',
      border: 'border-teal-200 dark:border-teal-800',
      accent: 'text-teal-600 dark:text-teal-400',
    },
    description:
      'Standardized obstetric triage (ACOG / MEOWS), gestational age calculation, severe preeclampsia/eclampsia risk stratification, vaginal bleeding, and fetal heart tone monitoring.',
    clinicalGuidelines: 'ACOG Practice Bulletin No. 222 (Gestational Hypertension & Preeclampsia)',
    typicalSpecialists: ['Obstetrician / Gynecologist', 'Maternal-Fetal Medicine Specialist', 'Neonatologist'],
    symptomTree: {
      id: 'obgyn_root',
      label: 'Obstetric & Gynecologic Emergency Presentation',
      description: 'Acute obstetric symptoms, third trimester complications, labor or severe hypertensive crisis',
      riskWeight: 4,
      children: [
        {
          id: 'obgyn_severe_hypertension_preeclampsia',
          label: 'Preeclampsia with Severe Features / Impending Eclampsia',
          description: 'Systolic BP ≥ 160 or Diastolic BP ≥ 110, severe persistent headache, visual scotomata, clonus',
          riskWeight: 10,
          isRedFlag: true,
          alertText: 'IMPENDING SEIZURE RISK: Prepare IV Magnesium Sulfate loading dose (4-6g over 20 min) + IV Labetalol / Hydralazine.',
          children: [
            {
              id: 'obgyn_neurological_symptoms',
              label: 'Intractable Frontal Headache, Photophobia, Flashing Lights (Scotomata)',
              description: 'Cerebral edema manifestation of severe preeclampsia',
              riskWeight: 10,
              isRedFlag: true,
            },
            {
              id: 'obgyn_epigastric_pain',
              label: 'Severe Right Upper Quadrant / Epigastric Pain',
              description: 'Hepatic capsular distension; High risk of HELLP syndrome or hepatic rupture',
              riskWeight: 9,
              isRedFlag: true,
            },
          ],
        },
        {
          id: 'obgyn_third_trimester_bleeding',
          label: 'Third Trimester Vaginal Bleeding',
          description: 'Abruptio placentae, placenta previa, or vasa previa',
          riskWeight: 9,
          isRedFlag: true,
          alertText: 'DO NOT PERFORM DIGITAL VAGINAL EXAM until placental location confirmed by Ultrasound!',
          children: [
            {
              id: 'obgyn_painful_dark_bleeding',
              label: 'Painful Dark Bleeding with "Board-Like" Rigid Hypertonic Uterus (Abruption)',
              description: 'Retroplacental hemorrhage and severe maternal-fetal compromise',
              riskWeight: 10,
              isRedFlag: true,
            },
            {
              id: 'obgyn_painless_bright_bleeding',
              label: 'Painless Bright Red Bleeding (Placenta Previa)',
              description: 'Cervical os covered by placental tissue',
              riskWeight: 8,
            },
          ],
        },
        {
          id: 'obgyn_active_labor_srom',
          label: 'Active Labor / Spontaneous Rupture of Membranes (SROM)',
          description: 'Regular painful contractions, fluid leak, impending delivery',
          riskWeight: 6,
          children: [
            {
              id: 'obgyn_cord_prolapse',
              label: 'Cord Prolapse (Palpable pulsating loop of umbilical cord in vagina)',
              description: 'Direct compression cuts off fetal oxygenation',
              riskWeight: 10,
              isRedFlag: true,
              alertText: 'OBSTETRIC CATASTROPHE: Manually elevate presenting fetal head off cord and roll to OR for STAT Emergent C-Section.',
            },
          ],
        },
      ],
    },
    guidedQuestions: [
      {
        id: 'gestational_age_weeks',
        label: 'Current Gestational Age (Weeks + Days)',
        category: 'timeline',
        type: 'select',
        required: true,
        options: [
          { value: 'under_24w', label: '< 24 Weeks (Pre-Viable / Early Second Trimester)', riskScore: 5 },
          { value: '24_to_33w', label: '24 to 33+6 Weeks (Preterm - Antenatal Corticosteroids indicated)', riskScore: 8, isRedFlag: true, alertMessage: 'Administer Betamethasone 12mg IM for fetal lung maturity.' },
          { value: '34_to_36w', label: '34 to 36+6 Weeks (Late Preterm)', riskScore: 6 },
          { value: '37_to_41w', label: '37 to 41+6 Weeks (Term Pregnancy)', riskScore: 3 },
          { value: 'over_42w', label: '≥ 42 Weeks (Post-Term Pregnancy)', riskScore: 6 },
        ],
      },
      {
        id: 'obstetric_blood_pressure',
        label: 'Triage Blood Pressure Reading',
        category: 'severity',
        type: 'select',
        required: true,
        options: [
          { value: 'normal_under_140_90', label: 'Normal (< 140/90 mmHg)', riskScore: 1 },
          { value: 'mild_140_159_90_109', label: 'Gestational Hypertension (140-159 / 90-109 mmHg)', riskScore: 6 },
          { value: 'severe_over_160_110', label: 'SEVERE RANGE HYPERTENSION (≥ 160/110 mmHg on 2 readings 15m apart)', riskScore: 10, isRedFlag: true, alertMessage: 'ACOG SEVERE HYPERTENSION BUNDLE: Administer IV Labetalol 20mg or IV Hydralazine 10mg within 30-60 min.' },
        ],
      },
      {
        id: 'fetal_heart_rate_category',
        label: 'Bedside Electronic Fetal Monitoring (FHR Category)',
        category: 'examination',
        type: 'select',
        required: true,
        options: [
          { value: 'category_1_normal', label: 'Category I: Normal Baseline 110-160 bpm, Moderate variability, Accelerations present', riskScore: 1 },
          { value: 'category_2_indeterminate', label: 'Category II: Indeterminate (Minimal variability, variable decelerations, fetal tachycardia)', riskScore: 6 },
          { value: 'category_3_abnormal', label: 'Category III: ABNORMAL (Recurrent late decelerations, bradycardia < 110 bpm, sinusoidal pattern)', riskScore: 10, isRedFlag: true, alertMessage: 'EMERGENT FETAL DISTRESS: Left lateral tilt, high-flow O2, prepare for emergent delivery.' },
        ],
      },
      {
        id: 'gravida_para_history',
        label: 'Obstetric Parity (G_ P_ Living_)',
        category: 'primary_symptom',
        type: 'text',
        defaultValue: 'G2 P1 L1',
        helperText: 'E.g., G3 P2 A0 L2 (Gravida, Para, Abortus, Living Children).',
      },
    ],
    riskSignals: [
      {
        id: 'signal_severe_preeclampsia_eclampsia',
        title: 'SEVERE PREECLAMPSIA / SEIZURE PROPHYLAXIS ALERT',
        severity: 'CRITICAL',
        triggerDescription: 'BP ≥ 160/110 mmHg with headache, visual changes, or hyperreflexia',
        guidelineReference: 'ACOG Practice Bulletin No. 222',
        immediateAction: 'Initiate IV Magnesium Sulfate 4g IV loading dose in 100mL over 20 min, followed by 2g/hr maintenance infusion. Target BP reduction with IV Labetalol or Oral Nifedipine.',
        badgeColor: 'bg-rose-600 text-white',
        conditionChecker: (answers) => answers['obstetric_blood_pressure'] === 'severe_over_160_110',
      },
      {
        id: 'signal_fetal_bradycardia_cat3',
        title: 'Category III Fetal Heart Rate Emergency',
        severity: 'CRITICAL',
        triggerDescription: 'Persistent severe fetal bradycardia or recurrent late decelerations',
        guidelineReference: 'NICHD Fetal Monitoring Guidelines',
        immediateAction: 'Notify Labor & Delivery Attending and Neonatal Resuscitation Team (NRP). Place patient in left lateral position, stop oxytocin, bolus IV fluids.',
        badgeColor: 'bg-amber-600 text-white animate-pulse',
        conditionChecker: (answers) => answers['fetal_heart_rate_category'] === 'category_3_abnormal',
      },
    ],
    specialtyHistory: [
      {
        id: 'ob_history_group',
        title: 'Obstetric History, Rh Status & Scar Integrity',
        description: 'Prior uterine surgery, Rh factor, and previous preeclampsia',
        fields: [
          {
            key: 'rh_factor_antibody',
            label: 'Maternal Blood Type & Rh Factor Status',
            type: 'select',
            options: ['O-Positive (Rh+)', 'A-Positive (Rh+)', 'B-Positive (Rh+)', 'AB-Positive (Rh+)', 'O-Negative (Rh- Rhogam candidate)', 'A-Negative (Rh-)', 'B-Negative (Rh-)', 'Unknown'],
            defaultValue: 'O-Positive (Rh+)',
            clinicalImpact: 'Rh-negative mothers with bleeding require Rh(D) Immune Globulin (RhoGAM).',
          },
          {
            key: 'prior_cesarean_scar',
            label: 'Prior Cesarean Section or Uterine Surgery',
            type: 'select',
            options: ['None (Prior Vaginal Deliveries Only / Nulliparous)', '1 Prior Low-Transverse Cesarean (TOLAC/VBAC candidate)', '2+ Prior Cesarean Deliveries (Elective Repeat C-Section)', 'Prior Classical / Vertical Uterine Scar (High Rupture Risk)'],
            defaultValue: 'None (Prior Vaginal Deliveries Only / Nulliparous)',
            clinicalImpact: 'Classical uterine scars strictly contraindicate labor trial due to uterine rupture risk.',
          },
          {
            key: 'prior_preeclampsia_gdm',
            label: 'Previous Pregnancy Complications',
            type: 'multiselect',
            options: ['Prior Preeclampsia / Eclampsia', 'Gestational Diabetes Mellitus', 'Preterm Delivery (< 34 weeks)', 'Postpartum Hemorrhage (PPH)', 'None'],
          },
        ],
      },
    ],
  },
];
