import { SurgicalChainCase } from '@/lib/types/surgical-chain';

export const INITIAL_SURGICAL_CHAIN_CASES: SurgicalChainCase[] = [
  {
    id: 'ot-01',
    room: 'OT Suite 1 (Cardiothoracic)',
    roomId: 'room-ot-01',
    procedureName: 'Off-Pump Coronary Artery Bypass Graft (CABG x3)',
    cptCode: 'CPT 33512',
    patientName: 'Robert Martinez',
    patientMrn: 'GH-2026-1042',
    patientId: 'p-1002',
    age: 63,
    gender: 'Male',
    leadSurgeon: 'Dr. Sarah Jenkins, FACS',
    surgeonId: 'usr-surg-01',
    anesthesiologist: 'Dr. Marcus Vance, MD',
    anesthesiologistId: 'usr-anes-01',
    scrubNurse: 'Sister Clara Oswald, RN',
    circulatingNurse: 'Sister Martha Jones, RN',
    startTime: '08:30 AM',
    durationMinutes: 240,
    currentStage: 'PROCEDURE',
    stageStatuses: {
      SURGICAL_REQUEST: 'COMPLETED',
      ELIGIBILITY: 'COMPLETED',
      CREDENTIAL_CHECK: 'COMPLETED',
      PRIVILEGE_CHECK: 'COMPLETED',
      STAFFING: 'COMPLETED',
      RESOURCE_CHECK: 'COMPLETED',
      OT_AVAILABILITY: 'COMPLETED',
      SCHEDULING: 'COMPLETED',
      PRE_OP: 'COMPLETED',
      WHO_CHECKLIST: 'COMPLETED',
      PROCEDURE: 'IN_PROGRESS',
      SIGN_OUT: 'PENDING',
      PACU_RESERVATION: 'PENDING',
      PACU_HANDOFF: 'PENDING',
      RECOVERY: 'PENDING',
      BED_TRANSFER: 'PENDING',
      TURNAROUND: 'PENDING',
    },
    safetyGates: {
      eligibilityPassed: true,
      credentialsVerified: true,
      privilegesVerified: true,
      staffingRatioPassed: true,
      sterileResourcesPassed: true,
      otRoomAvailable: true,
      whoSignInCompleted: true,
      whoTimeOutCompleted: true,
      whoSignOutCompleted: false,
      pacuBedReservedAtomic: false,
    },
    credentialRecord: {
      licenseActive: true,
      boardCertification: 'American Board of Thoracic Surgery',
      deaRegistrationValid: true,
      malpracticeCoverageActive: true,
      verifiedAt: '2026-09-23 07:15 AM',
    },
    privilegeRecord: {
      privilegeDelineationCode: 'CTS-CABG-ADV-01',
      procedureAuthorized: true,
      proctoringRequired: false,
      proctoringSignedOff: true,
      approvedByCredentialsCommittee: 'Verified by Medical Director',
    },
    resourceRecord: {
      cssdSterilityBarcode: 'CSSD-TRAY-2026-9812A',
      implantsAvailableAndVerified: true,
      bloodUnitsCrossmatched: 4,
      specialEquipmentReady: true,
    },
  },
  {
    id: 'ot-02',
    room: 'OT Suite 2 (Orthopedics & Joint)',
    roomId: 'room-ot-02',
    procedureName: 'Total Hip Arthroplasty (Posterior Approach)',
    cptCode: 'CPT 27130',
    patientName: 'Eleanor Vance',
    patientMrn: 'GH-2026-4492',
    patientId: 'p-1001',
    age: 71,
    gender: 'Female',
    leadSurgeon: 'Dr. Aris Thorne, MD',
    surgeonId: 'usr-surg-02',
    anesthesiologist: 'Dr. Elena Drake, MD',
    anesthesiologistId: 'usr-anes-02',
    scrubNurse: 'Nurse James Holden, RN',
    circulatingNurse: 'Nurse Naomi Nagata, RN',
    startTime: '10:00 AM',
    durationMinutes: 120,
    currentStage: 'PACU_RESERVATION',
    stageStatuses: {
      SURGICAL_REQUEST: 'COMPLETED',
      ELIGIBILITY: 'COMPLETED',
      CREDENTIAL_CHECK: 'COMPLETED',
      PRIVILEGE_CHECK: 'COMPLETED',
      STAFFING: 'COMPLETED',
      RESOURCE_CHECK: 'COMPLETED',
      OT_AVAILABILITY: 'COMPLETED',
      SCHEDULING: 'COMPLETED',
      PRE_OP: 'COMPLETED',
      WHO_CHECKLIST: 'COMPLETED',
      PROCEDURE: 'COMPLETED',
      SIGN_OUT: 'COMPLETED',
      PACU_RESERVATION: 'IN_PROGRESS',
      PACU_HANDOFF: 'PENDING',
      RECOVERY: 'PENDING',
      BED_TRANSFER: 'PENDING',
      TURNAROUND: 'PENDING',
    },
    safetyGates: {
      eligibilityPassed: true,
      credentialsVerified: true,
      privilegesVerified: true,
      staffingRatioPassed: true,
      sterileResourcesPassed: true,
      otRoomAvailable: true,
      whoSignInCompleted: true,
      whoTimeOutCompleted: true,
      whoSignOutCompleted: true,
      pacuBedReservedAtomic: false,
    },
    credentialRecord: {
      licenseActive: true,
      boardCertification: 'American Board of Orthopedic Surgery',
      deaRegistrationValid: true,
      malpracticeCoverageActive: true,
      verifiedAt: '2026-09-23 08:00 AM',
    },
    privilegeRecord: {
      privilegeDelineationCode: 'ORTHO-THA-IND-01',
      procedureAuthorized: true,
      proctoringRequired: false,
      proctoringSignedOff: true,
      approvedByCredentialsCommittee: 'Verified by Medical Director',
    },
    resourceRecord: {
      cssdSterilityBarcode: 'CSSD-TRAY-2026-4401X',
      implantsAvailableAndVerified: true,
      bloodUnitsCrossmatched: 2,
      specialEquipmentReady: true,
    },
  },
  {
    id: 'ot-03',
    room: 'OT Suite 3 (Laparoscopic & GI)',
    roomId: 'room-ot-03',
    procedureName: 'Laparoscopic Cholecystectomy with Cholangiogram',
    cptCode: 'CPT 47563',
    patientName: 'Sofia Chen',
    patientMrn: 'GH-2026-7731',
    patientId: 'p-1003',
    age: 31,
    gender: 'Female',
    leadSurgeon: 'Dr. Michael Chang, MD',
    surgeonId: 'usr-surg-03',
    anesthesiologist: 'Dr. Marcus Vance, MD',
    anesthesiologistId: 'usr-anes-01',
    scrubNurse: 'Nurse Emma Watson, RN',
    circulatingNurse: 'Sister Clara Oswald, RN',
    startTime: '11:45 AM',
    durationMinutes: 75,
    currentStage: 'WHO_CHECKLIST',
    stageStatuses: {
      SURGICAL_REQUEST: 'COMPLETED',
      ELIGIBILITY: 'COMPLETED',
      CREDENTIAL_CHECK: 'COMPLETED',
      PRIVILEGE_CHECK: 'COMPLETED',
      STAFFING: 'COMPLETED',
      RESOURCE_CHECK: 'COMPLETED',
      OT_AVAILABILITY: 'COMPLETED',
      SCHEDULING: 'COMPLETED',
      PRE_OP: 'COMPLETED',
      WHO_CHECKLIST: 'IN_PROGRESS',
      PROCEDURE: 'PENDING',
      SIGN_OUT: 'PENDING',
      PACU_RESERVATION: 'PENDING',
      PACU_HANDOFF: 'PENDING',
      RECOVERY: 'PENDING',
      BED_TRANSFER: 'PENDING',
      TURNAROUND: 'PENDING',
    },
    safetyGates: {
      eligibilityPassed: true,
      credentialsVerified: true,
      privilegesVerified: true,
      staffingRatioPassed: true,
      sterileResourcesPassed: true,
      otRoomAvailable: true,
      whoSignInCompleted: true,
      whoTimeOutCompleted: true,
      whoSignOutCompleted: false,
      pacuBedReservedAtomic: false,
    },
  },
  {
    id: 'ot-04',
    room: 'OT Suite 4 (Emergency & General)',
    roomId: 'room-ot-04',
    procedureName: 'Exploratory Laparotomy & Splenorrhaphy (Trauma)',
    cptCode: 'CPT 49000',
    patientName: 'Zubair Ahmed',
    patientMrn: 'GH-2026-3108',
    patientId: 'p-1004',
    age: 26,
    gender: 'Male',
    leadSurgeon: 'Dr. Sarah Jenkins, FACS',
    surgeonId: 'usr-surg-01',
    anesthesiologist: 'Dr. Elena Drake, MD',
    anesthesiologistId: 'usr-anes-02',
    scrubNurse: 'Sister Clara Oswald, RN',
    circulatingNurse: 'Nurse James Holden, RN',
    startTime: '01:15 PM',
    durationMinutes: 90,
    currentStage: 'PRE_OP',
    stageStatuses: {
      SURGICAL_REQUEST: 'COMPLETED',
      ELIGIBILITY: 'COMPLETED',
      CREDENTIAL_CHECK: 'COMPLETED',
      PRIVILEGE_CHECK: 'COMPLETED',
      STAFFING: 'COMPLETED',
      RESOURCE_CHECK: 'COMPLETED',
      OT_AVAILABILITY: 'COMPLETED',
      SCHEDULING: 'COMPLETED',
      PRE_OP: 'IN_PROGRESS',
      WHO_CHECKLIST: 'PENDING',
      PROCEDURE: 'PENDING',
      SIGN_OUT: 'PENDING',
      PACU_RESERVATION: 'PENDING',
      PACU_HANDOFF: 'PENDING',
      RECOVERY: 'PENDING',
      BED_TRANSFER: 'PENDING',
      TURNAROUND: 'PENDING',
    },
    safetyGates: {
      eligibilityPassed: true,
      credentialsVerified: true,
      privilegesVerified: true,
      staffingRatioPassed: true,
      sterileResourcesPassed: true,
      otRoomAvailable: true,
      whoSignInCompleted: false,
      whoTimeOutCompleted: false,
      whoSignOutCompleted: false,
      pacuBedReservedAtomic: false,
    },
  },
];
